### ISSUE TITLE
Codecov's Report Data will be stored in GCS

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#100]
KPI

report data moved from reports column to GCS

after deployment: 0 use cases of database entering maintence mode due to report writing

write up on moving data to GCS: https://l.codecov.dev/2PvHA0

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/70
- [ ] https://github.com/codecov/platform-team/issues/31
- [ ] https://github.com/codecov/platform-team/issues/119
- [ ] https://github.com/codecov/engineering-team/issues/189
- [ ] https://github.com/codecov/engineering-team/issues/190
```
