### ISSUE TITLE
Improve performance of repo syncing

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#101]
Syncing repos is one of the very first interactions a user has with Codecov. Depending on the size of their org and various other factors like volume in our queues, this syncing task can take a very long time. Gio did a fantastic investigation on the why’s behind this in CODE-2666: Repo Sync task is slow
CLOSED
 and we should follow up on possible ways of speeding up the process. A slow sync leads people to think Codecov is broken or otherwise slow in general and is a continual friction point, especially for larger users. 

Problem:

The current repo sync task is slow and can take a long time to complete.

Solution:

There are several ways we can improve repo sync performance:

Needs investigation, but from Gio’s initial analysis, there’s an opportunity to refactor the sync_repos task for improved performance

Additionally it seems like maybe there’s some queuing/task routing opportunity to potentially make sure these tasks get picked up sooner

[front-end] Improving processing indicators to better set user expectations and give real-time progress updates during repo syncing

[front-end] Implementing streaming data to the front-end instead of waiting for all data to load. This allows users to see and interact with partial data while the sync is still ongoing
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/6
- [ ] https://github.com/codecov/platform-team/issues/7
- [ ] https://github.com/codecov/engineering-team/issues/259
```
