### ISSUE TITLE
Get Test Selection to Beta-able Release

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#104]
This epic is to collect outstanding issues required to get test selection to a beta release.
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/41
- [ ] https://github.com/codecov/platform-team/issues/40
- [ ] https://github.com/codecov/platform-team/issues/65
- [ ] https://github.com/codecov/platform-team/issues/21
- [ ] https://github.com/codecov/platform-team/issues/64
- [ ] https://github.com/codecov/engineering-team/issues/188
- [ ] https://github.com/codecov/engineering-team/issues/191
- [ ] https://github.com/codecov/engineering-team/issues/192
- [ ] https://github.com/codecov/engineering-team/issues/353
```
