### ISSUE TITLE
[Client] Create bundle analysis onboarding steps

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#1043]
We need to create some onboarding steps in case users have not yet setup bundle analysis. These steps will be based off of the current getting started guides for the different frameworks.
```[tasklist]
### Tasks
- [x] Create vite onboarding
- [x] Create rollup onboarding
- [ ] Create webpack onboarding
```
