### ISSUE TITLE
Audit: Ben Vinegar Codecov integration walkthrough (+ Spencer)

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#1049]
## Audit review

Looking at steps to integrate Codecov to a project. Auditor notes: 

- i got momentarily confused that the "Ask for a Demo" CTA meant i couldnt just sign up (02:30)
- i got stuck a bit when i couldn't find my repo in the list of projects (04:38)
- i had trouble figuring out where to put the GitHub Actions .yaml command (08:45)
- the instructions assumed i was generating coverage reports, which i was not (i had to figure this out by inspecting the build output) (16:31)

https://youtu.be/LX3GZFliq8o

@spalmurray-codecov [write up](https://www.notion.so/sentry/Spencer-s-Codecov-onboarding-notes-f8dd90409dd44594bd1a5c8378bcfc46)

## Next steps

- Review video and team feedback
     - @codecovdesign [review, notes, and issue follow ups ](https://github.com/codecov/engineering-team/issues/1049#issuecomment-1893917788)
- Create issues documenting cited problems
- Proposals for issues fixes

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1050
- [ ] https://github.com/codecov/engineering-team/issues/1051
- [ ] https://github.com/codecov/engineering-team/issues/1053
- [ ] https://github.com/codecov/engineering-team/issues/1054
- [ ] https://github.com/codecov/engineering-team/issues/1056
- [ ] https://github.com/codecov/engineering-team/issues/1057
- [ ] https://github.com/codecov/engineering-team/issues/1104
- [ ] https://github.com/codecov/engineering-team/issues/1105
- [ ] https://github.com/codecov/engineering-team/issues/1107
- [ ] https://github.com/codecov/engineering-team/issues/1124
- [ ] https://github.com/codecov/engineering-team/issues/1126
- [ ] https://github.com/codecov/engineering-team/issues/235
- [ ] https://github.com/codecov/engineering-team/issues/1226
- [ ] https://github.com/codecov/engineering-team/issues/1227
- [ ] https://github.com/codecov/engineering-team/issues/1334
```

**Comment by codecovdesign** [comment]
@codecovdesign review:

 4:20 - 4:40 auditor notices distracting "syncing" (ToDo create issue)
5:00 interprests "active" and "inactive" as sorting vs configuration status (ToDo create issue for copy)
 
<img width="530" alt="Screenshot 2024-01-16 at 7 55 39 AM" src="https://github.com/codecov/engineering-team/assets/87861036/9dac2788-49f5-4f47-972a-1ba1825bd96c">

**Comment by codecovdesign** [comment]
closing epic as all issues have been addressed
