### ISSUE TITLE
Patch coverage as the only default

### ISSUE THREAD

**Issue by aj-codecov** [codecov/engineering-team#1078]
**Problem to solve**
Project coverage is a metric that we opt users into by default, but isn't needed by many of our users. An individual developer really cares most about what's in their pull request (patch coverage), not what the coverage of their entire repo is. Coincidentally, if your patch coverage is high you will improve project coverage, so if you're keeping your patch coverage high your project coverage won't suffer. Project coverage is also difficult to consistently get right for many customers as it's impacted not just by what happens in a pull request, but also by the setup of an org's CI, much of which is out of the purview of the average developer. This makes troubleshooting project coverage hard and frustrating. 

**Proposed Solution**

1. Remove project coverage checks as a default for new Codecov users.
2. Remove project coverage from the PR comment entirely and default only to patch coverage for new users

```[tasklist]
### UX considerations
- [ ] How do we want to handle the dissonance of seeing project coverage on UI and not on the PR for new users?
- [ ] How do we have a new user turn project coverage reporting back on?
- [ ] https://github.com/codecov/engineering-team/issues/1058
```

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1387
- [ ] https://github.com/codecov/engineering-team/issues/1388
- [ ] https://github.com/codecov/engineering-team/issues/1389
- [ ] https://github.com/codecov/engineering-team/issues/1390
- [ ] https://github.com/codecov/engineering-team/issues/1391
```

**Comment by codecovdesign** [comment]
need error messaging / on the UI and PR comment share that we weren't able to receive a coverage report bc GH rate limited us.

- audit current experience
     - check pr comment for existing messaging?
- create error messaging
     - suggestion CLI and token (repo guide + UI general)

**Comment by rohan-at-sentry** [comment]
If a new org onboards, by default they will only see project coverage on the PR. 

If they subsequently turn on flags and components - they will see project coverage



![Image](https://github.com/codecov/engineering-team/assets/142251589/3eec1b65-f0b3-4cf8-aca0-9fc880811ff6)

Opened https://github.com/codecov/engineering-team/issues/1656 to address
