### ISSUE TITLE
Open Source Codecov

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#108]
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/11
- [ ] https://github.com/codecov/platform-team/issues/12
- [ ] https://github.com/codecov/platform-team/issues/13
- [ ] https://github.com/codecov/platform-team/issues/37
- [ ] https://github.com/codecov/platform-team/issues/73
- [ ] https://github.com/codecov/platform-team/issues/109
- [ ] https://github.com/codecov/platform-team/issues/110
- [ ] https://github.com/codecov/platform-team/issues/111
- [ ] https://github.com/codecov/platform-team/issues/118
- [ ] https://github.com/codecov/platform-team/issues/117
```
