### ISSUE TITLE
Replace API Repo

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#109]
```[tasklist]
### Tasks
- [x] Move existing repo to repo-archive
- [x] Create new repo
- [x] Push sanitized version of repo
- [x] Configure repo with safeguards
- [x] Update Codecov settings in db
- [x] Copy circleci env to new repo
```
