### ISSUE TITLE
Bundle Analysis in the UI (post MVP) - V0.5

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#1093]
BA over time, deep dive into problematic bundles etc
```[tasklist]
### API - Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1190
- [ ] https://github.com/codecov/engineering-team/issues/1191
- [ ] https://github.com/codecov/engineering-team/issues/1068
- [ ] https://github.com/codecov/engineering-team/issues/1237
- [ ] https://github.com/codecov/engineering-team/issues/1193
- [ ] https://github.com/codecov/engineering-team/issues/1194
- [ ] https://github.com/codecov/engineering-team/issues/1234
- [ ] https://github.com/codecov/engineering-team/issues/1195
- [ ] https://github.com/codecov/engineering-team/issues/1197
- [ ] https://github.com/codecov/engineering-team/issues/1198
- [ ] https://github.com/codecov/engineering-team/issues/1192
- [ ] https://github.com/codecov/engineering-team/issues/1196
- [ ] https://github.com/codecov/engineering-team/issues/1199
- [ ] https://github.com/codecov/engineering-team/issues/1067
- [ ] https://github.com/codecov/engineering-team/issues/1268
- [ ] https://github.com/codecov/engineering-team/issues/1364
- [ ] https://github.com/codecov/engineering-team/issues/1367
```

```[tasklist]
### Client - Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1213
- [ ] https://github.com/codecov/engineering-team/issues/1200
- [ ] https://github.com/codecov/engineering-team/issues/1212
- [ ] https://github.com/codecov/engineering-team/issues/1215
- [ ] https://github.com/codecov/engineering-team/issues/1201
- [ ] https://github.com/codecov/engineering-team/issues/1202
- [ ] https://github.com/codecov/engineering-team/issues/1203
- [ ] https://github.com/codecov/engineering-team/issues/1204
- [ ] https://github.com/codecov/engineering-team/issues/1205
- [ ] https://github.com/codecov/engineering-team/issues/1206
- [ ] https://github.com/codecov/engineering-team/issues/1207
- [ ] https://github.com/codecov/engineering-team/issues/1208
- [ ] https://github.com/codecov/engineering-team/issues/1209
- [ ] https://github.com/codecov/engineering-team/issues/1210
- [ ] https://github.com/codecov/engineering-team/issues/1211
- [ ] https://github.com/codecov/engineering-team/issues/1214
```

```[tasklist]
### Bundler Plugins - Tasks
- [ ] codecov/codecov-javascript-bundler-plugins#52
- [ ] codecov/codecov-javascript-bundler-plugins#50
```
```[tasklist]
### Investigation / Planning - Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1118
- [ ] https://github.com/codecov/engineering-team/issues/1115
- [ ] https://github.com/codecov/engineering-team/issues/1121
```

**Comment by aj-codecov** [comment]
https://www.figma.com/file/IeW6e2YY0vwjIjlHYCBFac/Bundle-Analysis?type=design&node-id=511-2934&mode=design&t=iHBqPESoGW317myO-0

V0.5 (launch week release) will be the above link, but only:
- branch selection
- bundle selector
- high level summary information
- bundle assets

We're cutting out the sunburst, size over time graph, the bar chart, and the sliders to get this out the door quickly - the visualizations are still planned for the V1 of BA.
