### ISSUE TITLE
Codecov CLI Release

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#113]
This epic is for tracking issues we need to solve before releasing the codecov-cli

jira: https://codecovio.atlassian.net/browse/CODE-2637
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/45
- [ ] https://github.com/codecov/platform-team/issues/46
- [ ] https://github.com/codecov/platform-team/issues/47
- [ ] https://github.com/codecov/platform-team/issues/25
- [ ] https://github.com/codecov/platform-team/issues/26
- [ ] https://github.com/codecov/platform-team/issues/28
- [ ] https://github.com/codecov/platform-team/issues/29
- [ ] https://github.com/codecov/platform-team/issues/43
- [ ] https://github.com/codecov/platform-team/issues/27
- [ ] https://github.com/codecov/platform-team/issues/44
- [ ] https://github.com/codecov/platform-team/issues/30
- [ ] https://github.com/codecov/platform-team/issues/181
```
