### ISSUE TITLE
PR Comment Updates

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#125]
Epic outlines steps toward release of new comment, as per the Q3 review

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/8
- [ ] https://github.com/codecov/platform-team/issues/9
- [ ] https://github.com/codecov/platform-team/issues/123
- [ ] https://github.com/codecov/engineering-team/issues/296
- [ ] https://github.com/codecov/platform-team/issues/122
- [ ] https://github.com/codecov/engineering-team/issues/610
```

**Comment by trent-codecov** [comment]
Unassigning milestone until Apps team work is complete.
