### ISSUE TITLE
Codecov slack app should not use “Slack” in its name or domain name other than to note itself as a third-party integration.

### ISSUE THREAD

**Issue by RulaKhaled** [codecov/engineering-team#1276]
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/infrastructure-team/issues/134
- [ ] https://github.com/codecov/engineering-team/issues/1668
- [ ] https://github.com/codecov/infrastructure-team/issues/298
```
