### ISSUE TITLE
JTBD maps audit

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1311]
##### Description
To align our customers' expectations at each step, we need to identify the improvements, gaps and opportunities in the JTBD maps. https://github.com/codecov/engineering-team/issues/917

## Possible solution
Create individual issues to track and investigate the improvements work.

#### Action Checklist for Issue Creation
- [ ] Add the design project (to the right under "projects" > settings icon > select "design team")
- [ ] Share in relevant Slack channel (#discuss-codecov-product-design) for visiblity
- [ ] Add targeted launch date/delivery date as/if needed

#### Additional Information

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1332
- [ ] https://github.com/codecov/engineering-team/issues/1333
```
