### ISSUE TITLE
The "Team" plan (FKA Turn off project coverage by default)

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#132]
KPIs
* PR comment redesigned to not include project coverage
* New PR comment released to X% of customers (determined by product)
https://github.com/codecov/roadmap/issues/37
```[tasklist]
### Platform Tasks
- [ ] https://github.com/codecov/platform-team/issues/133
- [ ] https://github.com/codecov/platform-team/issues/134
- [ ] https://github.com/codecov/platform-team/issues/141
- [ ] https://github.com/codecov/engineering-team/issues/369
- [ ] https://github.com/codecov/engineering-team/issues/446
- [ ] https://github.com/codecov/engineering-team/issues/447
- [ ] https://github.com/codecov/engineering-team/issues/675
```
```[tasklist]
### Applications Tasks
- [ ] https://github.com/codecov/engineering-team/issues/604
- [ ] https://github.com/codecov/engineering-team/issues/771
```
[Designs](https://www.figma.com/file/9fHZis0dg7pKAQZt8fAGZO/Patch-only-experimentation?type=design&node-id=1-238&mode=design&t=lC4xel3qWfjkPMv5-0)
