### ISSUE TITLE
PR comment capable of not displaying project coverage

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#133]
First phase of the work is a new PR comment that features ONLY patch coverage and a files changed table. Additionally we need to include a link to provide feedback and a link to direct people how to get the old PR comment back. 

We will not roll this out to more than 5% of users at first. 

The following image is what we're looking to implement. 
- Note there is only "Patch" coverage in the coverage percentage column of the table. 
- Designs for feedback link at the bottom are forthcoming. 
- We need a clear and easy way to switch the PR comment back for some users
  - Yaml config is fine
- Rollout should be on a per org basis, so different users within the same org shouldn't see different PR comments.

<img width="1529" alt="Screenshot 2023-08-07 at 12 42 47 PM" src="https://github.com/codecov/engineering-team/assets/95712206/3d775b6a-b671-47a6-90f3-aac67dc51117">

```[tasklist]
### Tasks
- [x] Add config option to the codecov yaml to exclude project coverage
- [x] Modify PR comment to only display patch coverage
- [ ] Work with product/design on adding feedback link to PR comment for this change.
```

[Designs](https://www.figma.com/file/9fHZis0dg7pKAQZt8fAGZO/Patch-only-experimentation?type=design&node-id=1%3A238&mode=design&t=Qi9Vnv9rnSy0pjss-1)
