### ISSUE TITLE
Adding in GraphQL Descriptions to the API

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#1349]
Currently we do not have any description comments for our GraphQL API, this makes working with it a little harder, as we can only use the name of the field to describe what we're requesting, and that is not always clear. The goal of this epic is to address this issue, and go through the API and add in these comment descriptions to all of the GraphQL files in the API.

You can read the [Ariadne Description implementation here](https://ariadnegraphql.org/docs/documenting-schema)

And if you're interested you can do some further reading about these descriptions in the GraphQL Spec [here](https://spec.graphql.org/June2018/#sec-Descriptions)

```[tasklist]
### Files to update
- [ ] Add descriptions for `branch/branch.graphql`
- [ ] Add descriptions for `bundle_analysis/base.graphql`
- [ ] Add descriptions for `bundle_analysis/comparison.graphql`
- [ ] Add descriptions for `bundle_analysis/report.graphql`
- [ ] Add descriptions for `commit/commit.graphql`
- [ ] Add descriptions for `comparison/comparison.graphql`
- [ ] Add descriptions for `component/component.graphql`
- [ ] Add descriptions for `component_comparison/component_comparison.graphql`
- [ ] Add descriptions for `config/config.graphql`
- [ ] Add descriptions for `coverage_totals/coverage_totals.graphql`
- [ ] Add descriptions for `enums/commit_error_code.graphql`
- [ ] Add descriptions for `enums/commit_error_type.graphql`
- [ ] Add descriptions for `enums/commit_state.graphql`
- [ ] Add descriptions for `enums/coverage_line.graphql`
- [ ] Add descriptions for `enums/goal_onboarding.graphql`
- [ ] Add descriptions for `enums/impacted_files_parameters.graphql`
- [ ] Add descriptions for `enums/login_providers.graphql`
- [ ] Add descriptions for `enums/measurement_interval.graphql`
- [ ] Add descriptions for `enums/measurement_type.graphql`
- [ ] Add descriptions for `enums/ordering_direction.graphql`
- [ ] Add descriptions for `enums/path_contents_value.graphql`
- [ ] Add descriptions for `enums/pull_request_state.graphql`
- [ ] Add descriptions for `enums/repository_ordering.graphql`
- [ ] Add descriptions for `enums/repository_token.graphql`
- [ ] Add descriptions for `enums/sync_provider.graphql`
- [ ] Add descriptions for `enums/tier_name.graphql`
- [ ] Add descriptions for `enums/trial_status.graphql`
- [ ] Add descriptions for `enums/type_projects.graphql`
- [ ] Add descriptions for `enums/upload_error_enum.graphql`
- [ ] Add descriptions for `enums/upload_state.graphql`
- [ ] Add descriptions for `enums/upload_type.graphql`
- [ ] Add descriptions for `enums/yaml_stats.graphql`
- [ ] Add descriptions for `errors/errors.graphql`
- [ ] Add descriptions for `file/file.graphql`
- [ ] Add descriptions for `flag/flag.graphql`
- [ ] Add descriptions for `flag_comparison/flag_comparison.graphql`
- [ ] Add descriptions for `impacted_file/impacted_file.graphql`
- [ ] Add descriptions for `inputs/activate_measurements.graphql`
- [ ] Add descriptions for `inputs/branches_set_filters.graphql`
- [ ] Add descriptions for `inputs/bundle_analysis_filters.graphql`
- [ ] Add descriptions for `inputs/cancel_trial.graphql`
- [ ] Add descriptions for `inputs/commit_set_filters.graphql`
- [ ] Add descriptions for `inputs/components_filters.graphql`
- [ ] Add descriptions for `inputs/create_api_token.graphql`
- [ ] Add descriptions for `inputs/create_user_token.graphql`
- [ ] Add descriptions for `inputs/delete_flag.graphql`
- [ ] Add descriptions for `inputs/delete_session.graphql`
- [ ] Add descriptions for `inputs/flag_comparison_filters.graphql`
- [ ] Add descriptions for `inputs/flag_set_filters.graphql`
- [ ] Add descriptions for `inputs/impacted_files_filters.graphql`
- [ ] Add descriptions for `inputs/measurement_set_filters.graphql`
- [ ] Add descriptions for `inputs/onboard_user.graphql`
- [ ] Add descriptions for `inputs/organization_set_filters.graphql`
- [ ] Add descriptions for `inputs/path_contents_filters.graphql`
- [ ] Add descriptions for `inputs/pulls_set_filters.graphql`
- [ ] Add descriptions for `inputs/regenerate_org_upload_token.graphql`
- [ ] Add descriptions for `inputs/regenerate_repository_token.graphql`
- [ ] Add descriptions for `inputs/repository_set_filters.graphql`
- [ ] Add descriptions for `inputs/revoke_user_token.graphql`
- [ ] Add descriptions for `inputs/save_sentry_state.graphql`
- [ ] Add descriptions for `inputs/segments_filter.graphql`
- [ ] Add descriptions for `inputs/set_yaml_on_owner.graphql`
- [ ] Add descriptions for `inputs/start_trial.graphql`
- [ ] Add descriptions for `line_comparison.graphql`
- [ ] Add descriptions for `me/me.graphql`
- [ ] Add descriptions for `measurement/measurement.graphql`
- [ ] Add descriptions for `mutation/activate_measurements/activate_measurements.graphql`
- [ ] Add descriptions for `mutation/cancel_trial/cancel_trial.graphql`
- [ ] Add descriptions for `mutation/create_api_token/create_api_token.graphql`
- [ ] Add descriptions for `mutation/create_user_token/create_user_token.graphql`
- [ ] Add descriptions for `mutation/delete_flag/delete_flag.graphql`
- [ ] Add descriptions for `mutation/delete_session/delete_session.graphql`
- [ ] Add descriptions for `mutation/onboard_user/onboard_user.graphql`
- [ ] Add descriptions for `mutation/regenerate_org_upload_token/regenerate_org_upload_token.graphql`
- [ ] Add descriptions for `mutation/regenerate_repository_token/regenerate_repository_token.graphql`
- [ ] Add descriptions for `mutation/revoke_user_token/revoke_user_token.graphql`
- [ ] Add descriptions for `mutation/save_sentry_state/save_sentry_state.graphql`
- [ ] Add descriptions for `mutation/save_terms_agreement/save_terms_agreement.graphql`
- [ ] Add descriptions for `mutation/set_yaml_on_owner/set_yaml_on_owner.graphql`
- [ ] Add descriptions for `mutation/start_trial/start_trial.graphql`
- [ ] Add descriptions for `mutation/sync_with_git_provider/sync_with_git_provider.graphql`
- [ ] Add descriptions for `mutation/update_default_organization/update_default_graphql_organization.graphql`
- [ ] Add descriptions for `mutation/update_profile/update_profile.graphql`
- [ ] Add descriptions for `mutation/mutation.graphql`
- [ ] Add descriptions for `owner/owner.graphql`
- [ ] Add descriptions for `path_contents/path_contents.graphql`
- [ ] Add descriptions for `plan/plan.graphql`
- [ ] Add descriptions for `plan_representation/plan_representation.graphql`
- [ ] Add descriptions for `profile/profile.graphql`
- [ ] Add descriptions for `pull/pull.graphql`
- [ ] Add descriptions for `query/query.graphql`
- [ ] Add descriptions for `repository/repository.graphql`
- [ ] Add descriptions for `repository_config/repository_config.graphql`
- [ ] Add descriptions for `segment_comparison/segment_comparison.graphql`
- [ ] Add descriptions for `self_hosted_license/self_hosted_license.graphql`
- [ ] Add descriptions for `session/session.graphql`
- [ ] Add descriptions for `upload/upload.graphql`
- [ ] Add descriptions for `user/user.graphql`
- [ ] Add descriptions for `user_token/user_token.graphql`
```
