### ISSUE TITLE
[API] Migrate Remaining REST APIs to GraphQL

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#1351]
Currently we have a couple of REST endpoints, such as `account-details`. We need to investigate and find out which REST endpoints remain and if they have already been transitioned over, or have been partially moved over and need to be completed.

To accomplish this will require a couple of steps:

1. Find the potential REST endpoints that we can move over, or those that have started being moved.
2. Update the GraphQL API to support this data
3. Update Gazebo to use these new fields
4. Remove the REST endpoints

>[!note]
>There are a couple of REST endpoints used for self-hosted that will need to remain as REST endpoints. These are mainly around grabbing admins, and user details iirc. As well we cannot remove the public API REST endpoints.

```[tasklist]
### Invesitgation
- [x] Investigate remaining REST Endpoint
- [x] Investigate whether the endpoints have already been moved to GrahpQL, or if a subset of fields have been moved
- [x] Create tickets below
```

```[tasklist]
### REST APIs to be transitioned to GraphQL
- [ ] https://github.com/codecov/engineering-team/issues/1464
- [ ] https://github.com/codecov/engineering-team/issues/1465
- [ ] https://github.com/codecov/engineering-team/issues/1467
- [ ] https://github.com/codecov/engineering-team/issues/1470
```

```[tasklist]
### Update Gazebo to use new GQL fields
- [ ] https://github.com/codecov/engineering-team/issues/1469
- [ ] https://github.com/codecov/engineering-team/issues/1471
- [ ] https://github.com/codecov/engineering-team/issues/1472
- [ ] https://github.com/codecov/engineering-team/issues/1473
- [ ] https://github.com/codecov/engineering-team/issues/1474
```

```[tasklist]
### REST API's to be Removed
- [ ] https://github.com/codecov/engineering-team/issues/1468
- [ ] https://github.com/codecov/engineering-team/issues/1502
```

**Comment by rohitvinnakota-codecov** [comment]
https://docs.codecov.com/reference/root_list

These are a list of public APIs that we cannot remove
