### ISSUE TITLE
ISSUE: user wants to see change trends and delta

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#1413]
## Problem to solve

When analyzing the bundle data, users described desire to see the "delta" and/or "change" of assets over time and between commits/branches.

https://github.com/codecov/engineering-team/assets/87861036/715c9e61-ee8d-4ba8-b6e9-63b347ee7596

https://github.com/codecov/engineering-team/assets/87861036/412408f9-cdba-42c1-b660-f0173bc9c7e0

https://github.com/codecov/engineering-team/assets/87861036/ffce4255-1935-4c12-8a89-ed03c0f2891d

## Solution

At repo level explore showing changes over time, changes from last commit, and/or changes at release level (issue TODO)

Consider longer term implications too as under review in: https://github.com/codecov/engineering-team/issues/1420

[view designs](https://www.figma.com/file/3MvVYLFtBK1nCjEduz8Del/GH-1413?type=design&node-id=1%3A238&mode=design&t=YdLKtKEO77DJuh50-1) + [engineering investigation](https://www.notion.so/sentry/Change-Trends-and-Deltas-bd017025575c4874b2b4dd794a0290af)
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1698
```

```[tasklist]
### Backend ingestion
- [ ] https://github.com/codecov/engineering-team/issues/1767
- [ ] https://github.com/codecov/engineering-team/issues/1768
- [ ] https://github.com/codecov/engineering-team/issues/1765
- [ ] https://github.com/codecov/engineering-team/issues/1766
- [ ] https://github.com/codecov/engineering-team/issues/1769
- [ ] https://github.com/codecov/engineering-team/issues/1770
- [ ] https://github.com/codecov/engineering-team/issues/1771
- [ ] https://github.com/codecov/engineering-team/issues/1825
- [ ] https://github.com/codecov/engineering-team/issues/1875
- [ ] https://github.com/codecov/engineering-team/issues/1846
```

```[tasklist]
### Backend Retrieval
- [ ] https://github.com/codecov/engineering-team/issues/1772
- [ ] https://github.com/codecov/engineering-team/issues/1773
- [ ] https://github.com/codecov/engineering-team/issues/1774
- [ ] https://github.com/codecov/engineering-team/issues/1775
- [ ] https://github.com/codecov/engineering-team/issues/1976
```

```[tasklist]
### UI Changes
- [ ] https://github.com/codecov/engineering-team/issues/1800
- [ ] https://github.com/codecov/engineering-team/issues/1801
- [ ] https://github.com/codecov/engineering-team/issues/1802
- [ ] https://github.com/codecov/engineering-team/issues/1803
- [ ] https://github.com/codecov/engineering-team/issues/1804
- [ ] https://github.com/codecov/engineering-team/issues/1805
- [ ] https://github.com/codecov/engineering-team/issues/2047
- [ ] https://github.com/codecov/engineering-team/issues/2048
```

**Comment by codecovdesign** [comment]
some ideation of how this could help:

**user wants to see changes over time**

- timeline graph: line graph showing the evolution of bundle sizes over the project's history
     - bundle (and/or grouping/filtering aggregate) level (macro overview)
     - individual asset (micro overview), such as sparkline of trend data per full lifespan
- custom time ranges: allow users to select and examine specific time periods

**user wants to see how asset changed from last time of change**

- delta indicators: show the size difference since the last change (per commit) next to each modified asset
     - link to commits: connect to the corresponding commit for quick access and troubleshooting
     - Vu: more helpful at the PR/commit level / at the repo level would be helpful to see at the (engineer dependent) more interested in macro level
          - scope down to PR comment for up/down?
          - alternative for the individual asset at the repo level: show % of bundle size, who added it, commit history (the delta) more interested in the fuller history of it
- visual cues / filtering: use indicators to highlight increases and decreases in size to help user at a glance + filtering

**Comment by nicholas-codecov** [comment]
Anything around tracking individual assets going to be extremely difficult to accomplish atm, we need to do some work to figure this out as with each change to an asset, the file name changes so it is hard to track over time.
