### ISSUE TITLE
SSO to Codecov (via Okta)

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#144]
KPIs
* Successful implementation and usage of Single Sign-On (SSO) via Okta for Codecov
* At least 1 user using it
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/145
- [ ] https://github.com/codecov/platform-team/issues/146
- [ ] https://github.com/codecov/engineering-team/issues/450
- [ ] https://github.com/codecov/platform-team/issues/147
- [ ] https://github.com/codecov/platform-team/issues/182
```
