### ISSUE TITLE
Audit: uploads

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#1450]
## Problem to solve

Audit the current UX and touchpoints of uploads: user expectations,  how they are used, how uploads are visualized, and how users troubleshoot with them. 

In Codecov, uploads refer to the process of sending coverage reports generated repo's your CI/CD pipeline or local testing environment to the Codecov platform. These reports are typically generated after running tests on codebase, specific to programming language used. Here is the general workflow of an upload:

1. Generate coverage report: after running tests, a coverage report is generated detailing which code was executed.
2. Upload to Codecov: this report is uploaded to Codecov, typically as part of your CI/CD pipeline.
3. Codecov analysis: codecov processes and analyzes the coverage data.
4. Insights: developers receive insights into code coverage, highlighting areas for potential improvement.

```[tasklist]
### Bugs
- [ ] https://github.com/codecov/codecov-cli/issues/351
- [ ] https://github.com/codecov/engineering-team/issues/1475
```

```[tasklist]
### Related issues
- [ ] https://github.com/codecov/engineering-team/issues/1086
- [ ] https://github.com/codecov/engineering-team/issues/201
- [ ] https://github.com/codecov/engineering-team/issues/1128
- [ ] https://github.com/codecov/engineering-team/issues/1534
- [ ] https://github.com/codecov/engineering-team/issues/1535
- [ ] https://github.com/codecov/engineering-team/issues/203
- [ ] https://github.com/codecov/engineering-team/issues/1536
- [ ] https://github.com/codecov/engineering-team/issues/264
- [ ] https://github.com/codecov/engineering-team/issues/1061
- [ ] Rename "Uploads" to "Coverage reports" in the UI and doc
- [ ] https://github.com/codecov/engineering-team/issues/2499
- [ ] https://github.com/codecov/engineering-team/issues/2498
```

```[tasklist]
### Backend improvements
- [ ] https://github.com/codecov/engineering-team/issues/1520
```

**Comment by Adal3n3** [comment]
Here is the design exploration for uploads. We will review it tomorrow to see which direction we should move forward. 
Figma: [link](https://www.figma.com/file/ipt8D8zYKYWOhhlavVT1Ev/GH-1450?type=design&node-id=1-2&mode=design)

![Screenshot 2024-04-03 at 4 13 48 PM](https://github.com/codecov/engineering-team/assets/152432831/9f276479-a0fd-4c16-8195-3bd210b0e0bd)
![Screenshot 2024-04-03 at 4 15 56 PM](https://github.com/codecov/engineering-team/assets/152432831/47d70cdf-456d-4dbb-930d-a83691298ad3)
![Screenshot 2024-04-03 at 4 15 27 PM](https://github.com/codecov/engineering-team/assets/152432831/c851ccfd-52b2-4af7-8880-3376917d848c)

**Comment by Adal3n3** [comment]
@codecovdesign @aj-codecov @rohan-at-sentry @katia-sentry 

Here are the prioritized upload issues for your review. Please add your comments here if you have thoughts on the ordering. Happy to move around the ordering of the issues if you think one is more important than others.
![Screenshot 2024-04-09 at 12 44 17 PM](https://github.com/codecov/engineering-team/assets/152432831/1f45ea0c-1a0e-4b76-a199-bd803577f505)

To view the combined designs view, go [here](https://www.figma.com/file/ipt8D8zYKYWOhhlavVT1Ev/GH-1450?type=design&node-id=1-2&mode=design)
![Screenshot 2024-04-09 at 12 48 34 PM](https://github.com/codecov/engineering-team/assets/152432831/80ec2b3f-4e7a-4c63-ab3a-ade5ffe9aba7)

To view the individual design changes that's based on the issue, you can use the issues here or navigate to the pages on Figma. 
![Screenshot 2024-04-09 at 12 58 17 PM](https://github.com/codecov/engineering-team/assets/152432831/52a058c4-962c-4220-93ea-b8fa62f394ec)

**Comment by Adal3n3** [comment]
Just want to glue some documents here:
1. [How a commit gets from upload to report to notification](https://www.notion.so/sentry/How-a-commit-gets-from-upload-to-report-to-notification-0c176f66302b4563af4d86b57eee4aa4)
2. This is the real [Processing upload](https://github.com/codecov/worker/blob/a8d7e5571b54fe39b421eaa757036fb5a55725b3/tasks/upload.py#L180-L230)

![Screenshot 2024-04-09 at 2 23 36 PM](https://github.com/codecov/engineering-team/assets/152432831/1975feda-c06c-43b8-a1ea-6a153498cd22)

**Comment by codecovdesign** [comment]
@spalmurray-codecov for sprint 150 could you review this with @Adal3n3, then we can groom some of the iterations for future sprints?
cc @katia-sentry

**Comment by Adal3n3** [comment]
@codecovdesign @katia-sentry, @spalmurray-codecov and I had synced 2 weeks ago and I didn't post a note here. I should have posted a note for our sync. 

| issue        | Eng work (day)  | Note  |
| ------------- | -----:| ------------- |
| https://github.com/codecov/engineering-team/issues/201 | 1 | - | 
| https://github.com/codecov/engineering-team/issues/1128 | 2-3  | Pagination with filter takes a sprint so we are going for without pagination filter and including search by flag name, etc |
| https://github.com/codecov/engineering-team/issues/1535 | 1-2 | Need design tweak |
| https://github.com/codecov/engineering-team/issues/203  | 1 | - |
|https://github.com/codecov/engineering-team/issues/1536  | 10 days | Bulk download might take around a sprint and require API work. No need platform work |
| https://github.com/codecov/engineering-team/issues/2499 | deprioritize | we didn't review this issue


Beside 1536 and 2499 we can wrap this issue in a sprint.
