### ISSUE TITLE
Onboarding into Failed Tests

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1494]
Static Onboarding Page as outlined in the following figma page

https://www.figma.com/file/HsTf9J1aYx0ur9kwH8MXrm/GH-1341?type=design&node-id=168-7655&mode=design&t=vfTBh4dXMecSoMpG-0 **(this is for design exploration and sizing)**

Note the new component in the screenshot here
(cleaner and better UX - unclear if a component previously exists that makes it easy to build this out fast)
![image](https://github.com/codecov/engineering-team/assets/142251589/29c1642e-1ae8-4bdd-a15d-45eda3dd0f8e)

This page is effectively static

### The latest design for onboarding:
Figma: [link](https://www.figma.com/file/MbfQ7BE0ENmUOPRIe6GMvV/GH-1494?type=design&node-id=1-2&mode=design) 
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1696
- [ ] https://github.com/codecov/engineering-team/issues/1730
- [ ] https://github.com/codecov/engineering-team/issues/1732
- [ ] https://github.com/codecov/engineering-team/issues/1822
- [ ] https://github.com/codecov/engineering-team/issues/1823
- [ ] https://github.com/codecov/engineering-team/issues/1824
- [ ] https://github.com/codecov/engineering-team/issues/1736
- [ ] https://github.com/codecov/engineering-team/issues/1731
- [ ] https://github.com/codecov/engineering-team/issues/1733
- [ ] https://github.com/codecov/engineering-team/issues/1734
- [ ] https://github.com/codecov/engineering-team/issues/1735
```

**Comment by codecovdesign** [comment]
@Adal3n3 assigning you this

- update issue description with scope changes
- add designs (only parts that will be updated)

**Comment by codecovdesign** [comment]
@spalmurray-codecov just pinging you for visibility, your in-progress guide work (formatting, cards, radio, styling, etc) will apply here in these updates too. worth pinging @RulaKhaled @Adal3n3 when that work is shipped for their visibility too!

**Comment by Adal3n3** [comment]
Thanks @spalmurray-codecov for implementing this radio button w description component on issue   https://github.com/codecov/engineering-team/issues/1439. Can't wait to use it on the failed tests onboarding implementation.

Screenshot provided by Spencer:
![Screenshot 2024-05-01 at 14 13 23](https://github.com/codecov/engineering-team/assets/152432831/f7fefaa2-867a-438b-bbb6-bb2910104f32)
