### ISSUE TITLE
Auto refund on cancelation immediately after start of new billing cycle

### ISSUE THREAD

**Issue by aj-codecov** [codecov/engineering-team#1507]
**Problem to Solve:**
It's very common for someone to get hit with a charge for their next billing cycle and then immediately reach out to support to cancel and get a refund. This is common across all subscription based products. 

**Proposed Solution:**
We can reduce support workload by allowing automatic refunds when a person cancels within 24 hours of a new billing cycle when on a monthly billing cadence and within 72 hours for those on a yearly billing cadence. 
This should include some sort of messaging to the customer that we have refunded them and immediately canceled the rest of their sub. 

**Risk:**
We risk someone coming back to us and saying they canceled but still wanted to ride out the rest of the month, but I think this is a much smaller category of users than the problem we're attempting to solve. 
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1508
- [ ] https://github.com/codecov/engineering-team/issues/1813
- [x] Confirm any updates to baremetrics needed
- [x] Understand difference between downgrade and cancelation logic
```
Figma: [link](https://www.figma.com/design/WispRoZQs6rGwy0nrwN9xB/GH-1507?node-id=1-2)

**Comment by ajay-sentry** [comment]
Questions:

Is this only for sentry plan or for all customers?

Potential:
- UI updates needed?

**Comment by Adal3n3** [comment]
@aj-codecov 
- Will customers receive an email confirmation for their refund?
- In the UI, do we tell them anything about the refund after they cancel the plan?
- I scheduled a mini audit with you, Ajay and I to see what need to update on the UIs.

**Comment by Adal3n3** [comment]
Making a note here from the audit with @aj-codecov @ajay-sentry :
- This project will apply to all customers.
- Customers will receive an email confirmation of their refund.
- After the cancellation of their plan, they will receive a cancellation banner. Design needs to provide two banners: 1/ with refund info, 2/ without refund info.
- Use banner component for this banner.
<img width="738" alt="Screenshot 2024-05-21 at 3 47 39 PM" src="https://github.com/codecov/engineering-team/assets/152432831/47eae0bc-b453-4cd2-92de-46079e8da0fc">

**Comment by Adal3n3** [comment]
Here's the auto refund messaging in the UI. 
Moving to group review it on slack.
Figma: [link](https://www.figma.com/design/WispRoZQs6rGwy0nrwN9xB/GH-1507?node-id=1-2)
![Screenshot 2024-05-29 at 2 08 49 PM](https://github.com/codecov/engineering-team/assets/152432831/743166a1-86f4-460f-a88d-8b3a100daf7e)

**Comment by aj-codecov** [comment]
Re: #1813 - We've intentionally deprioritized this work in favor of better email support (email admins of the org) when we fail charges - #2348. We still may make it to this work in Q3 though.

**Comment by Adal3n3** [comment]
@calvin-codecov I see all the tasks here are closed so should we close this issue as well?
