### ISSUE TITLE
Test Analytics : Get to 100 customers by Q2 end

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1525]
```[tasklist]
### Quality of Life Improvements
- [ ] https://github.com/codecov/engineering-team/issues/1524
- [ ] https://github.com/codecov/engineering-team/issues/1550
- [ ] https://github.com/codecov/engineering-team/issues/1551
- [ ] https://github.com/codecov/engineering-team/issues/1672
- [ ] https://github.com/codecov/engineering-team/issues/1233
- [ ] https://github.com/codecov/engineering-team/issues/2068
```

```[tasklist]
### Growth Improvements
- [ ] https://github.com/codecov/engineering-team/issues/1526
- [ ] https://github.com/codecov/engineering-team/issues/1572
- [ ] https://github.com/codecov/engineering-team/issues/1713
```

```[tasklist]
### Ingestion Improvements (Not doing for now)
- [ ] https://github.com/codecov/engineering-team/issues/1486
```

```[tasklist]
### Test Analytics Features
- [ ] https://github.com/codecov/engineering-team/issues/1647
- [ ] https://github.com/codecov/engineering-team/issues/1648
- [ ] https://github.com/codecov/engineering-team/issues/2168
```

**Comment by rohan-at-sentry** [comment]
can defer `Ingestion Improvements`
