### ISSUE TITLE
Generate comment message in CLI

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/engineering-team#1528]
```[tasklist]
### Tasks
- [ ] Shorten file paths in shared lib
- [ ] Escape failure messages in shared lib
- [ ] Format comment in shared lib
```
