### ISSUE TITLE
Open Source Shelter and pkg with SH distro

### ISSUE THREAD

**Issue by aj-codecov** [codecov/engineering-team#1530]
**Problems to Solve:**
Shelter is not available for use in self hosted. We want to make it the sole source of ingest. We cannot do this without breaking self hosted until Shelter is available for use.

**Proposed Solution:**

```[tasklist]
### Tasks
- [ ] Decouple Shelter from GCP native resources
- [ ] Build Shelter as a docker container
- [ ] Prepare Shelter repository for being source available
- [ ] Make source available
```

Caveat:
- Shelter is coupled to GCP - make this decoupled from GCP and add an adapter layer for "any" cloud provider

**Comment by rohan-at-sentry** [comment]
@trent-codecov to add color
