### ISSUE TITLE
Create/Update Comment from CLI

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/engineering-team#1531]
```[tasklist]
### Tasks
- [ ] List existing comments API call
- [ ] Create comment API call
- [ ] Update comment API call
```
