### ISSUE TITLE
Investigate if Worker is capable of sending transactional email

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#154]
There is already a task created for this.
https://github.com/codecov/worker/blob/main/tasks/send_email.py
```[tasklist]
### Tasks
- [x] Investigate if task is usable
- [x] Determine level of effort needed to get task ready for production
- [x] Work with Trent/Eli to get Sendgrid credentials and discuss using Marketo
- [x] Determine how we will get email templates. Likely work with design.
```
