### ISSUE TITLE
Parse out test suite name from path

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1551]
```[tasklist]
### Tasks
- [ ] Parse out test name for tests run on `pytest`
- [ ] Parse out test name for tests run on `vitest`
- [ ] Parse out test name for tests run on `jest`
```

**Comment by rohan-at-sentry** [comment]
Captured [here](https://github.com/codecov/engineering-team/issues/1487). Closing as dupe
