### ISSUE TITLE
Codecov product will be capable of sending transactional email

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#156]
KPIs
* Worker is capable of sending emails
* API is capable of triggering an email via worker
* At least 1 email sent to a user

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/154
- [ ] https://github.com/codecov/platform-team/issues/157
- [ ] https://github.com/codecov/platform-team/issues/158
```

[Slack](https://sentry.slack.com/archives/C05PV9A7VC6)
