### ISSUE TITLE
Measure DB reliability - determine baseline metric and particular improvement goal around successfully processed reports

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#161]
KPIs
* Instrumentation added to allow tracking success of individual tasks in the system
* End to end success metric for uploads created
* Dashboard created for support/rev consumption
* Documentation created for how to instrument at Codecov
* at least 1 other eng creates a metric

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/165
- [ ] https://github.com/codecov/platform-team/issues/166
- [ ] https://github.com/codecov/platform-team/issues/167
- [ ] https://github.com/codecov/platform-team/issues/168
- [ ] https://github.com/codecov/platform-team/issues/169
- [ ] https://github.com/codecov/platform-team/issues/184
- [ ] https://github.com/codecov/engineering-team/issues/710
```
