### ISSUE TITLE
UI cleanup laundry list

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1639]
Design doc for reference: https://www.figma.com/file/lpCAamL0oUGKvVng0g7vex/GH-234?type=design&node-id=1-2&mode=design&t=iR8totq8VZOchuyP-0

```[tasklist]
### Tasks
- [x] Add a link to redirect from components tab on PR page to components tab on Repo page
- [x] Add latest commit under the branch selector
- [x] Disable the branch dropdown box on the not_configured/enable/backfilling views
- [x] When clicking "Enable component analytics" button it should reload the page (which would bring it to backfilling view)
- [x] Fix padding on the dropdowns section. The padding between the vertical line and dropdown and padding between the dropdown label and dropbown
- [x] Add table headers when showing the not_configured/enable/backfilling views
- [x] Last Uploaded table header row values should align to the left
- [x] The delete component modal message is not correct
- [x] Add a aria-label = "delete-{component_id}" to the trash can icon to delete
- [x] Update the message from 24 hour to 1 hour on the backfilling view
```
