### ISSUE TITLE
Ingest coverage results files and report on failed tests

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#164]
KPIs
* test results ingested
* some report in PR comment
* updated to CLI to support
* at least 1 user using

https://github.com/codecov/roadmap/issues/39
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/664
- [ ] https://github.com/codecov/engineering-team/issues/663
- [ ] https://github.com/codecov/engineering-team/issues/886
- [ ] https://github.com/codecov/engineering-team/issues/560
- [ ] Worker task for analyzing failed tests
```
