### ISSUE TITLE
AI PR review MVP

### ISSUE THREAD

**Issue by rohitvinnakota-codecov** [codecov/engineering-team#1658]
See [Notion](https://www.notion.so/sentry/AI-PR-Comment-Review-MVP-ce4f95b65bc64e58ab8ea9c76cb37405?p=b7b81d0b03014482ac2bad428d7d327d&pm=c) here.

We want to have a github app that is able to make comment suggestions on pull requests, enabled by an LLM. The first step will be to have these running on our internal repos. 

This epic will also encompass backend functionality, including decisions on data storage and possibly integrating with `Seer`. 
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/ai-review-prompt/issues/28
- [ ] https://github.com/codecov/ai-review-prompt/issues/30
- [ ] https://github.com/codecov/ai-review-prompt/issues/31
- [ ] https://github.com/codecov/ai-review-prompt/issues/27
- [ ] https://github.com/codecov/ai-review-prompt/issues/26
- [ ] https://github.com/codecov/ai-review-prompt/issues/25
- [ ] https://github.com/codecov/ai-review-prompt/issues/24
```
