### ISSUE TITLE
A few UI tweaks

### ISSUE THREAD

**Issue by JerrySentry** [codecov/engineering-team#1666]
```[tasklist]
### Tasks
- [x] The outbound link icon should be white for "Get started with components" button (see picture 1)
- [x] Give the table header a line, maybe at the bottom of colgroup (see picture 1)
- [x] On the backfill UI, there is an extra line below the branch selector (see picture 2)
```

Picture 1

![Screenshot 2024-04-26 at 8 50 59 AM](https://github.com/codecov/engineering-team/assets/142266253/bc2d90ca-4c7e-49b7-839b-9fa367a965ed)

Picture 2

![Screenshot 2024-04-26 at 8 58 28 AM](https://github.com/codecov/engineering-team/assets/142266253/6c6b18b8-b37c-4eb0-ac0d-af1acd80b486)
