### ISSUE TITLE
[Metrics] Signup to first commit metrics breakdown

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#1673]
**Is your feature request related to a problem? Please describe.**
The average signup completion rate (from signup to commit) is 2.8%. To increase from signup to commit, we are trying to figure out which task/step has the highest drop-off rate.

Notion doc: [link](https://www.notion.so/sentry/Metrics-Codecov-signup-to-commit-tasks-breakdown-0a799a7acb344bc2a2f49fc5c885f055)

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1674
- [ ] https://github.com/codecov/engineering-team/issues/1675
- [ ] https://github.com/codecov/engineering-team/issues/1676
- [ ] https://github.com/codecov/engineering-team/issues/1677
- [ ] https://github.com/codecov/engineering-team/issues/1678
- [ ] https://github.com/codecov/engineering-team/issues/1679
- [ ] https://github.com/codecov/engineering-team/issues/1710
```

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1828
- [ ] https://github.com/codecov/engineering-team/issues/1829
- [ ] https://github.com/codecov/engineering-team/issues/1830
- [ ] https://github.com/codecov/engineering-team/issues/1831
- [ ] https://github.com/codecov/engineering-team/issues/1832
```

**Comment by Adal3n3** [comment]
@katia-sentry @trent-codecov Can you help gather these 6 metrics?

**Comment by katia-sentry** [comment]
Sure thing! where should we sent these? Marketo? @Adal3n3

**Comment by Adal3n3** [comment]
Thanks, @katia-sentry! Is this [Marketo](https://github.com/getsentry/dbt-data-transform/blob/f87eb754763640488139637d89c1f7c8c7adfc4e/models/marts/sentry_retl/sentry_marketo.sql) where the data team get data for Looker? That sounds good to me.

Note from @trent-codecov:
- we can do 4, 5.1, maybe 5.2, and 10.
- 7 is impossible to retroactively get as we auto generate a token in our database. Therefore every user already has a token and we can't query for ones that are not created.
- 8 may be also impossible to get retroactively. I need to confirm. 

Can we get step 4, 5.1, maybe 5.2, and 10 metrics in current or the following sprint?

(cc @rohan-at-sentry @aj-codecov )

**Comment by katia-sentry** [comment]
@rohitvinnakota-codecov are we sending events for these already? wondering if we still need this issue open.

**Comment by rohitvinnakota-codecov** [comment]
> @rohitvinnakota-codecov are we sending events for these already? wondering if we still need this issue open.

All items have been implemented. closing issue
