### ISSUE TITLE
Codecov can ingest reports/webhooks during periods of DB downtime

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#170]
KPIs
* Spec created for implementation
* Create POC for uploads
* Uploads MVP usable in production
* Create POC for webhooks

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/platform-team/issues/171
- [ ] https://github.com/codecov/platform-team/issues/172
- [ ] https://github.com/codecov/platform-team/issues/173
- [x] Project Shelter: https://github.com/orgs/codecov/projects/34/views/1
```
