### ISSUE TITLE
Lint Enhancements (RUFF)

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#1716]
Add Ruff to Shared and API, turn on recommended rules one by one and fix related errors, identify other rules that maybe beneficial.

Related Design Doc: https://www.notion.so/sentry/Migrating-to-Ruff-bf528650b6d14fad8cb9964da7cafcbe

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1719
- [ ] https://github.com/codecov/engineering-team/issues/1720
- [x] Turn on recommended rules for API
- [x] Turn on recommended rules for Shared
- [x] Curate additional rule list across Shared/API/Worker
- [x] Add isort rules to API
- [x] https://github.com/codecov/engineering-team/issues/1836
- [x] https://github.com/codecov/engineering-team/issues/1837
- [ ] https://github.com/codecov/engineering-team/issues/1839
- [ ] https://github.com/codecov/engineering-team/issues/1844
- [ ] https://github.com/codecov/engineering-team/issues/1845
- [ ] https://github.com/codecov/engineering-team/issues/1852
- [ ] https://github.com/codecov/engineering-team/issues/1873
- [ ] https://github.com/codecov/engineering-team/issues/1882
- [ ] https://github.com/codecov/engineering-team/issues/1930
- [ ] https://github.com/codecov/engineering-team/issues/1931
- [ ] https://github.com/codecov/engineering-team/issues/1965
- [ ] https://github.com/codecov/engineering-team/issues/2050
- [ ] https://github.com/codecov/engineering-team/issues/2052
- [ ] https://github.com/codecov/engineering-team/issues/2396
- [ ] https://github.com/codecov/engineering-team/issues/3151
- [ ] https://github.com/codecov/engineering-team/issues/3277
- [ ] https://github.com/codecov/engineering-team/issues/3278
- [ ] https://github.com/codecov/engineering-team/issues/3279
```
