### ISSUE TITLE
[Codeowners] Discovery - Codeowners component mapping

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1739]
```[tasklist]
### Tasks
- [ ] Dig into codeowners format to ensure the approach in the parent issue will work
- [ ] Ensure components implementation will scale to the level needed
- [ ] Document how and where the mapping of codeowners->component will take place
```

**Comment by michelletran-sentry** [comment]
CODEOWNERS file can be a [max of 3mb](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-size). This means that for ~10000 lines, the user can have an average of 300 ASCII characters (or if including comments, then double that to 20000 lines, or 150 ASCII characters). I _think_ we can support the extra annotation per line in the format (unless the customer has a very weird format).

**Comment by michelletran-sentry** [comment]
Looking at the data in our database, it looks like we want to support 10x the number of components as our current maximum: https://metabase.codecov.dev/question/234-repos-with-the-most-components The repo that's most heavily using components has only 104 components at the moment. Outside the top 10, there are relatively few users of components (and they have less than 30 components).
