### ISSUE TITLE
[Accounts] Implement account settings functionality

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#1743]
Depends on #1533 

```[tasklist]
### Tasks
- [x] Add DB table for storing account settings
- [x] Add ability to store OKTA settings (client_id, client_secret, url, enabled, enforced?) on the new table
- [x] Add ability to query for these settings for a logged in user
```
