### ISSUE TITLE
Deprecate Segment

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#175]
KPIs
* Segment alternative found
* Segment alternative implemented
* Complete migration off of segment
```[tasklist]
### Platform Tasks
- [ ] https://github.com/codecov/platform-team/issues/179
- [ ] https://github.com/codecov/platform-team/issues/177
- [ ] https://github.com/codecov/platform-team/issues/178
- [ ] https://github.com/codecov/engineering-team/issues/467
- [ ] https://github.com/codecov/engineering-team/issues/468
- [ ] https://github.com/codecov/infrastructure-team/issues/142
- [ ] https://github.com/codecov/engineering-team/issues/559
```

```[tasklist]
### Applications Tasks
- [ ] https://github.com/codecov/engineering-team/issues/243
- [ ] https://github.com/codecov/engineering-team/issues/668
```

**Comment by katia-sentry** [comment]
Done on the Applications
