### ISSUE TITLE
Profile "heuristic 2" and ensure it scales for 50k tests

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#1752]
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1753
- [ ] https://github.com/codecov/engineering-team/issues/1789
- [ ] Report back on projected response time at 50k matriced tests
```
