### ISSUE TITLE
Update Banner use throughout Gazebo

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#1816]
Below is a non-exhaustive list. If you find another banner that needs to be updated, add it below! 

Typical Process for updating a banner is as follows:

**NOTE: Insert First PR Here for later people to copy from**
- Familiarize yourself with the Alert Component stories
- For Banner Headings and content, you'll follow one of the latter 4 stories
- For Banner with just Heading
  - Confirm with Adalene we want to keep that design of banner
  - If we do, add a Header story for next person (Remove this line if you complete this!)
  - Follow the Header story
- For Banners with just Content, follow the first story
- Take a screenshot before and after
- Try to minimize banner -> alert conversions to at the max, 5 per PR imo.

```[tasklist]
### Tasks
- [ ] OrgUploadToken.jsx
- [ ] ActivationBanner.jsx
- [ ] AdminBanner.jsx -> BundleAnalysis
- [ ] ErrorBanner.tsx -> BundleAnalysis
- [ ] FirstPullBanner.tsx
- [ ] BotErrorBanner.jsx
- [ ] ErrorBanner.tsx -> CommitDetailPage
- [ ] FirstPullBanner -> CommitDetailPage
- [ ] YamlErrorBanner -> CommitDetailPage
- [ ] YamlModalErrorBanner -> CommitDetailPage
- [ ] GitHubHelpBanner -> DefaultOrgSelector
- [ ] MissingMemberBanner -> MembersPage
- [ ] ExceededUploadsAlert
- [ ] GitHubConfigBanner
- [ ] ReachingUploadLimitAlert
- [ ] ErrorBanner -> PullRequestPage
- [ ] FirstPullBanner -> PullRequestPage
- [ ] ErrorBanner -> RepoPage
- [ ] InfoBanner
- [ ] IntroBlurb
- [ ] FreePlanSeatsLimitBanner
- [ ] PaidPlanSeatsLimitBanner
- [ ] TrialEligibleBanner
- [ ] IntroBlurb
- [ ] SyncingBanner
- [ ] TriggerSyncBanner
- [ ] FirstPullRequestBanner -> RepoPage
- [ ] MissingDesignatedAdmins
- [ ] SelfHostedLicenseExpiration
```
