### ISSUE TITLE
Audit: new sign up and GH app install (6/12) 

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#1899]
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1902
- [ ] https://github.com/codecov/engineering-team/issues/1903
- [ ] https://github.com/codecov/engineering-team/issues/1904
- [ ] https://github.com/codecov/engineering-team/issues/1905
- [ ] https://github.com/codecov/engineering-team/issues/1916
- [ ] https://github.com/codecov/engineering-team/issues/1906
- [ ] https://github.com/codecov/internal-issues/issues/692
- [ ] https://github.com/codecov/engineering-team/issues/1900
- [ ] https://github.com/codecov/engineering-team/issues/1909
- [ ] https://github.com/codecov/engineering-team/issues/1901
- [ ] https://github.com/codecov/engineering-team/issues/1911
```

**Comment by codecovdesign** [comment]
all issues resolved, closing epic
