### ISSUE TITLE
[M1] Rewrite Report model and merging logic in Rust

### ISSUE THREAD

**Issue by thomasrockhu-codecov** [codecov/engineering-team#1919]
Milestone 1 is the replacement of the Python `Report` class with a Rust/SQLite report under the hood in `UploadProcessorTask`.

At a high level, `UploadProcessorTask`:
- reads the commit's existing report JSON + chunks file into a Python `Report`
- creates a temporary `Report` with the contents of this upload (using `ReportBuilder`)
- merges the temporary `Report` into the existing `Report`
- saves the updated report JSON and chunks file

Conceptually, we want to replace `Report` and `ReportBuilder` with shims that work with new Rust+SQLite models, but only under the hood. We'll still use a report JSON + chunks file as input/output (we may not even save the SQLite database at this stage) and we'll still use the existing Python parsers for lcov, cobertura, etc. However, the actual implementation will be messier than simple shims due to some code reaching into internals of the Python report.

Using a disk-based SQLite database instead of an in-memory Python `Report` class under the hood should make memory usage more predictable during report processing. Future milestones will reduce memory usage even more raw uploads and individual coverage files to be streamed instead of bulk-loaded into memory.

The immediate potential downside of this milestone is that, by virtue of moving a lot of data from RAM to disk-based SQLite, some things may get slower. We'll keep an eye on this, and we have room to optimize.

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/793
- [ ] https://github.com/codecov/engineering-team/issues/794
- [ ] https://github.com/codecov/engineering-team/issues/795
- [ ] https://github.com/codecov/engineering-team/issues/2307
- [ ] https://github.com/codecov/engineering-team/issues/2308
- [x] https://github.com/codecov/engineering-team/issues/2959
- [x] https://github.com/codecov/engineering-team/issues/2960
```

**Comment by tnt-sentry** [comment]
Closing the Q3 version of the KR. We have the foundational work complete and will work to do the integration work at the end of Q4 or in Q1.
