### ISSUE TITLE
[Epic] Moving Bundle Analysis out of Beta

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#1932]
# Description

The goal of this epic is to finish up these remaining "must have" tickets to feel comfortable moving the plugins out of their beta status and into full production mode.

```[tasklist]
### Move out of beta requirements
- [ ] #1783
- [ ] #1707
- [ ] #1961
- [x] - https://github.com/codecov/engineering-team/issues/1783
- [ ] https://github.com/codecov/engineering-team/issues/1949
- [ ] https://github.com/codecov/engineering-team/issues/1950
- [x] Investigate bundle caching
- [ ] https://github.com/codecov/engineering-team/issues/2183
- [ ] https://github.com/codecov/engineering-team/issues/2195
- [ ] https://github.com/codecov/engineering-team/issues/2254
- [ ] https://github.com/codecov/engineering-team/issues/2402
```

```[tasklist]
### Beta Cleanup
- [ ] https://github.com/codecov/engineering-team/issues/1937
- [ ] https://github.com/codecov/engineering-team/issues/1938
- [ ] https://github.com/codecov/engineering-team/issues/1939
- [ ] https://github.com/codecov/engineering-team/issues/2440
- [ ] https://github.com/codecov/engineering-team/issues/2441
```

```[tasklist]
### Pre Merge Commit
- [ ] https://github.com/codecov/engineering-team/issues/2005
- [ ] https://github.com/codecov/engineering-team/issues/2006
- [ ] https://github.com/codecov/engineering-team/issues/2007
- [ ] https://github.com/codecov/engineering-team/issues/2008
- [ ] https://github.com/codecov/engineering-team/issues/2009
- [ ] https://github.com/codecov/engineering-team/issues/2010
- [ ] https://github.com/codecov/engineering-team/issues/2014
```

```[tasklist]
### Tokenless
- [ ] https://github.com/codecov/engineering-team/issues/2206
- [ ] https://github.com/codecov/engineering-team/issues/2207
- [ ] https://github.com/codecov/engineering-team/issues/2208
- [ ] https://github.com/codecov/engineering-team/issues/2209
```
