### ISSUE TITLE
Plan for migrate UI components from JS to TS

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#197]
Were intending to migrate to TypeScript. A migration of our UI components to TypeScript  is needed. This involves migrating our foundational UI building block components. By addressing these core elements, we will create a smoother pathway for migrating the rest of the codebase to TS. 

The goal is to create an epic that the team can tackle incrementally to complete the migration of our UI components to TypeScript
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/484
- [ ] https://github.com/codecov/engineering-team/issues/485
- [ ] https://github.com/codecov/engineering-team/issues/486
- [ ] https://github.com/codecov/engineering-team/issues/487
- [ ] https://github.com/codecov/engineering-team/issues/488
- [ ] https://github.com/codecov/engineering-team/issues/489
- [ ] https://github.com/codecov/engineering-team/issues/490
- [ ] https://github.com/codecov/engineering-team/issues/491
- [ ] https://github.com/codecov/engineering-team/issues/492
- [ ] https://github.com/codecov/engineering-team/issues/495
- [ ] https://github.com/codecov/engineering-team/issues/496
- [ ] https://github.com/codecov/engineering-team/issues/497
- [ ] https://github.com/codecov/engineering-team/issues/498
- [ ] https://github.com/codecov/engineering-team/issues/499
- [ ] https://github.com/codecov/engineering-team/issues/500
- [ ] https://github.com/codecov/engineering-team/issues/501
- [ ] https://github.com/codecov/engineering-team/issues/502
- [ ] https://github.com/codecov/engineering-team/issues/503
- [ ] https://github.com/codecov/engineering-team/issues/504
- [ ] https://github.com/codecov/engineering-team/issues/505
- [ ] https://github.com/codecov/engineering-team/issues/506
- [ ] https://github.com/codecov/engineering-team/issues/507
- [ ] https://github.com/codecov/engineering-team/issues/508
- [ ] https://github.com/codecov/engineering-team/issues/509
- [ ] https://github.com/codecov/engineering-team/issues/510
- [ ] https://github.com/codecov/engineering-team/issues/511
- [ ] https://github.com/codecov/engineering-team/issues/512
- [ ] https://github.com/codecov/engineering-team/issues/513
- [ ] https://github.com/codecov/engineering-team/issues/514
- [ ] https://github.com/codecov/engineering-team/issues/515
- [ ] https://github.com/codecov/engineering-team/issues/516
- [ ] https://github.com/codecov/engineering-team/issues/517
- [ ] https://github.com/codecov/engineering-team/issues/518
- [ ] https://github.com/codecov/engineering-team/issues/519
- [ ] https://github.com/codecov/engineering-team/issues/522
- [ ] https://github.com/codecov/engineering-team/issues/523
- [ ] https://github.com/codecov/engineering-team/issues/524
```
