### ISSUE TITLE
Ongoing Polish and Tweaks Epic

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#199]
#### Ongoing Polish Epic

This epic stores polish, tweaks, and bug issues that are small iterations and/or not part of larger quarterly epics. If they are not completed in the quarter, the open issues will be rolled over to the next quarter.

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/201
- [ ] https://github.com/codecov/engineering-team/issues/216
- [ ] https://github.com/codecov/engineering-team/issues/203
- [ ] https://github.com/codecov/engineering-team/issues/204
- [ ] https://github.com/codecov/engineering-team/issues/209
- [ ] https://github.com/codecov/engineering-team/issues/231
- [ ] https://github.com/codecov/engineering-team/issues/235
- [ ] https://github.com/codecov/engineering-team/issues/240
- [ ] https://github.com/codecov/engineering-team/issues/248
- [ ] https://github.com/codecov/engineering-team/issues/264
- [ ] https://github.com/codecov/engineering-team/issues/267
- [ ] https://github.com/codecov/engineering-team/issues/273
- [ ] https://github.com/codecov/platform-team/issues/160
- [ ] https://github.com/codecov/engineering-team/issues/282
- [ ] https://github.com/codecov/engineering-team/issues/349
- [ ] https://github.com/codecov/engineering-team/issues/356
- [ ] https://github.com/codecov/engineering-team/issues/355
- [ ] https://github.com/codecov/engineering-team/issues/370
- [ ] https://github.com/codecov/engineering-team/issues/402
- [ ] https://github.com/codecov/engineering-team/issues/750
- [ ] https://github.com/codecov/engineering-team/issues/867
- [ ] https://github.com/codecov/engineering-team/issues/888
- [ ] https://github.com/codecov/engineering-team/issues/895
- [ ] https://github.com/codecov/engineering-team/issues/923
- [ ] https://github.com/codecov/engineering-team/issues/941
```

```[tasklist]
### Tasks
```

**Comment by codecovdesign** [comment]
closing this as all the tasks are completed
