### ISSUE TITLE
Q3 Test analytics UI & PR

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#2028]
We are releasing flaky test detection in Q3. Customers will be able to see the flaky test label, flake rate, and flake pattern (e.g., test passed x times, failed x times). We have a strong understanding of the 'Test-fixing mode workflow' and the 'Test-performance workflow.' These two mental models focus on what developers need to fix a test vs. what they need to improve a test. 

PM doc: [link](https://www.notion.so/sentry/Test-Analytics-UI-show-all-test-analytics-not-just-failed-and-flakes-437edf617ae447fa8dda0ae8eb98fd57)

Figma: [link](https://www.figma.com/design/TcppABudxnslgEmaXm0B9O/GH-2028?node-id=1-2)

<Details><Summary>Design exploration for user testing</summary>

![Screenshot 2024-07-03 at 4 09 15 PM](https://github.com/codecov/engineering-team/assets/152432831/49524c3b-9d3c-426e-a11e-116036dbd5a9)
</details>

<Details><Summary>Latest Design</summary>

![Image](https://github.com/user-attachments/assets/c93dfea7-11cf-4ccd-8adb-9e0e83b233f7)

![Image](https://github.com/user-attachments/assets/98ceca29-5b79-4776-977c-dd1c1dc60ed3)

</details>

User testing feedback: [link](https://www.notion.so/sentry/Q3-Test-Analytics-feedback-report-bb11cdd1e97640a49f635ecdc68a391b?pvs=4)

```[tasklist]
### PR comment
- [ ] https://github.com/codecov/engineering-team/issues/2068
- [ ] https://github.com/codecov/engineering-team/issues/2180
- [ ] https://github.com/codecov/engineering-team/issues/2162
- [ ] https://github.com/codecov/internal-issues/issues/670
- [ ] https://github.com/codecov/engineering-team/issues/2218
- [ ] https://github.com/codecov/engineering-team/issues/2436
- [ ] https://github.com/codecov/engineering-team/issues/2470
- [ ] https://github.com/codecov/engineering-team/issues/2179
- [ ] https://github.com/codecov/engineering-team/issues/2186
- [ ] https://github.com/codecov/engineering-team/issues/2457
- [ ] https://github.com/codecov/engineering-team/issues/2264
- [ ] https://github.com/codecov/internal-issues/issues/826
```

```[tasklist]
### Dashboard UI
- [ ] https://github.com/codecov/engineering-team/issues/2151
- [ ] https://github.com/codecov/engineering-team/issues/2181
- [ ] https://github.com/codecov/engineering-team/issues/2242
- [ ] https://github.com/codecov/engineering-team/issues/2269
- [ ] https://github.com/codecov/engineering-team/issues/2401
- [ ] https://github.com/codecov/engineering-team/issues/2471
- [ ] https://github.com/codecov/engineering-team/issues/2528
- [x] Main branch: 30 days historical trend filter
- [x] Main branch: Test suites dropdown with search capability
- [x] Main branch: Flags dropdown with search capability
- [x] Main branch: Flake rate column and flake pattern
- [x] Main branch: 5 dashboard metrics
- [x] Feature branch: last test run compare to main
- [ ] https://github.com/codecov/engineering-team/issues/2163
- [x] Expired flake experience (no need anymore)
- [ ] https://github.com/codecov/engineering-team/issues/2078
- [ ] https://github.com/codecov/engineering-team/issues/2388
- [ ] https://github.com/codecov/engineering-team/issues/2406
- [x] UI search by test name
- [ ] Backlog: Display the latest failed time in the UI maybe next to the failed commits
- [ ] https://github.com/codecov/engineering-team/issues/2605
```

```[tasklist]
### Doc
- [x] Doc: On the setup flow add instruction on how to change Pytest test suites name on Junit XML (as an optional)
- [x] Doc: Explain the 30 days retentions section (changed it to 60 days)
- [x] Doc: Are we doing anything to improve the public API in q3?
- [x] Doc: Mention about flags setup (env setup)
- [ ] https://github.com/codecov/engineering-team/issues/2619
```
```[tasklist]
### Applications Team
- [ ] https://github.com/codecov/engineering-team/issues/2411
- [ ] https://github.com/codecov/engineering-team/issues/2413
- [ ] https://github.com/codecov/engineering-team/issues/2424
- [ ] https://github.com/codecov/engineering-team/issues/2431
- [ ] https://github.com/codecov/engineering-team/issues/2432
- [ ] https://github.com/codecov/engineering-team/issues/2668
- [ ] https://github.com/codecov/engineering-team/issues/2669
- [ ] https://github.com/codecov/engineering-team/issues/2670
- [ ] https://github.com/codecov/engineering-team/issues/2671
- [ ] https://github.com/codecov/engineering-team/issues/2662
- [ ] https://github.com/codecov/engineering-team/issues/2666
- [ ] https://github.com/codecov/engineering-team/issues/2409
- [ ] https://github.com/codecov/engineering-team/issues/2430
- [ ] https://github.com/codecov/engineering-team/issues/2635
- [ ] https://github.com/codecov/engineering-team/issues/2664
- [ ] https://github.com/codecov/engineering-team/issues/2663
- [ ] https://github.com/codecov/engineering-team/issues/2422
- [ ] https://github.com/codecov/engineering-team/issues/2657
- [ ] https://github.com/codecov/engineering-team/issues/2658
- [ ] https://github.com/codecov/engineering-team/issues/2425
- [ ] https://github.com/codecov/engineering-team/issues/2438
- [ ] https://github.com/codecov/engineering-team/issues/2660
- [ ] https://github.com/codecov/engineering-team/issues/2656
- [ ] https://github.com/codecov/engineering-team/issues/2452
- [ ] https://github.com/codecov/engineering-team/issues/2169
- [ ] https://github.com/codecov/engineering-team/issues/2408
- [ ] https://github.com/codecov/engineering-team/issues/2410
- [ ] https://github.com/codecov/engineering-team/issues/2412
- [ ] https://github.com/codecov/engineering-team/issues/2415
- [ ] https://github.com/codecov/engineering-team/issues/2416
- [ ] https://github.com/codecov/engineering-team/issues/2417
- [ ] https://github.com/codecov/engineering-team/issues/2418
- [ ] https://github.com/codecov/engineering-team/issues/2419
- [ ] https://github.com/codecov/engineering-team/issues/2420
- [ ] https://github.com/codecov/engineering-team/issues/2421
- [ ] https://github.com/codecov/engineering-team/issues/2414
- [ ] https://github.com/codecov/engineering-team/issues/2423
- [ ] https://github.com/codecov/engineering-team/issues/2427
- [ ] https://github.com/codecov/engineering-team/issues/2426
- [ ] https://github.com/codecov/engineering-team/issues/2429
- [ ] https://github.com/codecov/engineering-team/issues/2428
- [ ] https://github.com/codecov/engineering-team/issues/2706
- [ ] https://github.com/codecov/engineering-team/issues/2705
- [ ] Update public api
- [ ] https://github.com/codecov/engineering-team/issues/2707
- [ ] https://github.com/codecov/engineering-team/issues/2708
```

**Comment by ajay-sentry** [comment]
Polish Ticket here: https://github.com/codecov/engineering-team/issues/2690
