### ISSUE TITLE
Q3 Billing Updates

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#2057]
Baseline recovery % = 37.66% for year of June '23 to May '24

```[tasklist]
### Backlogs
- [ ] https://github.com/codecov/engineering-team/issues/1507
- [ ] https://github.com/codecov/engineering-team/issues/2348
- [ ] https://github.com/codecov/engineering-team/issues/2479
- [ ] https://github.com/codecov/engineering-team/issues/2200
- [ ] https://github.com/codecov/engineering-team/issues/2201
- [ ] https://github.com/codecov/engineering-team/issues/1797
- [ ] https://github.com/codecov/engineering-team/issues/1964
- [ ] https://github.com/codecov/engineering-team/issues/2502
- [ ] https://github.com/codecov/engineering-team/issues/1795
- [ ] https://github.com/codecov/engineering-team/issues/1796
- [ ] https://github.com/codecov/engineering-team/issues/1814
- [ ] https://github.com/codecov/engineering-team/issues/1810
- [ ] https://github.com/codecov/engineering-team/issues/1853
- [ ] https://github.com/codecov/internal-issues/issues/518
- [ ] https://github.com/codecov/engineering-team/issues/1811
- [ ] https://github.com/codecov/engineering-team/issues/1779
- [ ] https://github.com/codecov/engineering-team/issues/1759
```

```[tasklist]
### Platform Backlogs
- [ ] https://github.com/codecov/engineering-team/issues/2134
```

**Comment by aj-codecov** [comment]
@Adal3n3 @ajay-sentry I added 2543 above, should be a small design turn/tweak, but worth doing as we're currently telling people upgrades are more expensive than they really are.

**Comment by Adal3n3** [comment]
Closing this Q3 issue as it has been completed
