### ISSUE TITLE
Discovery: 1) GH codecov coverage action, and 2) appless codecov

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#2067]
## Problem to solve
Challenges with our brand awareness and expanding our product offerings; includes our adoption/growth efforts on various experimental features such as bundles, test analytics, AI review, etc. Here are some dynamics at play:

- **GitHub app installation requirement:** last year we moved to the requirement for an owner/admin to install the GitHub app, which we've observed can stall or even stop the momentum for organizations and their users moving forward with Codecov onboarding. Even if the installation process moves quickly, additional configuration for individual repositories is required. These friction points potentially slow the adoption of Codecov on the self-serve side.
- **Growth model:** while we have a strong enterprise growth model (100% YOY growth), it requires significant effort and does not support self-serve growth effectively (6% YOY growth). The business is focused on improving the self-serve portion.

## Discovery

The hypothesis is that providing users with our existing value set of coverage reports quickly and with minimal friction could significantly enhance brand awareness and adoption. This can be explored through two primary approaches and areas this issue will be exploring:
1. **[GitHub action experience](https://github.com/codecov/engineering-team/issues/2093):** if a Codecov GH action existed, how could this improve product awareness (improved visibility and more immediate value) and increase the subsequent pro/team plan adoption rate?
2. **[GitHub appless experience](https://github.com/codecov/engineering-team/issues/2092):** what could the user experience look like if the GitHub app wasn't required? How could we deliver value in this scenario?

These more frictionless mechanisms could help support establishing trust and delivering value more promptly, while creating better incentives for users to adopt the app and new experimental features.

### Steps to move forward

- [ ] **Team ideation and developing vision:** (kickoff schedule for 7/17)
   - Conduct brainstorming and team feedback solicitation sessions to generate ideas and further cultivate our product vision for an appless user experience and potential solutions. In addition to identifying open questions to answer...
   - Also, what metrics can we follow and/or what makes this initiative successful for the business?
   - Develop separate ideation tracks focusing on:
     - Appless user experience and possibilities.
     - Enhanced GitHub app experience, detailing what it would look like and how it could be leveraged for user growth.
    - potential alignment/conflict with ongoing efforts: https://github.com/codecov/engineering-team/issues/1899
    - what's missing?

- [ ] **Ideation translation:**
   - translate brainstormed ideas into drafts of flows/prototypes of what/how this could work.

- [ ] **Team review and identify next steps:**
   - Review the assets generated including: requirements, prototypes and flows with the team and gather feedback and identify the next steps...
```[tasklist]
### Q3 Appless
- [ ] https://github.com/codecov/engineering-team/issues/2092
- [ ] https://github.com/codecov/engineering-team/issues/2093
```

```[tasklist]
### Backlogs
- [ ] https://github.com/codecov/engineering-team/issues/2165
- [ ] https://github.com/codecov/engineering-team/issues/2221
```

**Comment by codecovdesign** [comment]
## kickoff sync notes 7/17 

<details><summary>notes</summary>

- eli: core problem is one of adoption, in toronto discussed building up a telemetry system. we wanted to confirm how much of a bottleneck the gh installation challenge. it's worth going deep 
- rohan: tldr is we sort of have signal that things fall apart at the app install. question is to what extent...
- kattia: zooming out a bit, consider if we could start with test analytics/bundle to experiment with this
     - rohan: considering the goal are we trying to solve for coverage specifically
          - alternatively, the suggestion supports the experimental growth features and worth exploring around
          - 

#### discovery
- what does  appless codecov look like?
- how is this different related to idea of codecov action

- GitHub appless experience: what could the user experience look like if the GitHub app wasn't required? How could we deliver value in this scenario?
     - goal: ability to login to codecov and have some mechanism for receiving coverage data. there shouldnt be a blocker to receiving coverage data. hypothesis is barriers to value are lifted and drives behavior for adoption. lastly, then how do we move them from this mechanism to adoption/installation of GH app
     - ideas of mechanism (constraints)
          - team concept (or ability to add orgs)
               - if able to have org, how could we import the repo (leverage team token and specify this in action and we'd know to pull that. this gets challenging, bc you could use token in multiple repos, but still we'd need that association)  
          - action
               - alternative: all that goes away^, user provides org sleg and we create a based on that 
          - rohan, other side to this: when talking about onboarding, the app is blocker, but once installing we have a lot of information of course repo, commits, PR etc - in this scenario your able to see repos to integrate with. 
               - how do we minimize the friction here - at minimum just think we are trading a class of problems are and see what we can do, for example, there really isn't a way to solve the token problem. 
                    - question: if token was added, what does the system api inform us about (if anything). could be that we have context of the repo > branch 
                    - flow/ideation
                         - entity creation (user creating team)
                         - system provide token related to entity/team
                         - user connect repo? what does system already know?        
- GitHub action experience: if a Codecov GH action existed, how could this improve product awareness (improved visibility and more immediate value) and increase the subsequent pro/team plan adoption rate?
      - existing action could be modified w/ CLI so it understand it could be leveraged that it's disconnected to GH. summary of potential iteration: 1) existing action, 2) leverage CLI, 3) revised to understand no GH app, 4) how to tie to reports to app and/or display
           - ToDo: what's the bare minimum that this step - offer this ability to the member that is otherwise waiting for the 

#### next steps
[related notes](https://www.notion.so/sentry/Appless-Codecov-c30479314c52476f96d143325b6cdaf4)
- how does onboarding change with these scenarios?
     - action if existed
     - consider adoption what does the push toward GH instal post initial setup 
          - challenges after github app is installed?
     - api confirmation of what is available IF app isn't installed 
- action may provide pr experience?
- app experience w/o connection? 
- we've thought a lot about coverage, but how do our other experiments looks like?


DRI: 
- design: initial foundation details/iteration kyle (short term GH action existence) and then adalene for longer term (team creation etc)
- PM: aj 
- ENG: rola, calvin, and spencer
     - tom for now platform/backend details 

</details>
