### ISSUE TITLE
Discovery 2: GitHub Appless Experience

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#2092]
_follow up from kickoff to discovery on 7/16, per epic: https://github.com/codecov/engineering-team/issues/2067_

## Context and overview:
We are exploring/hypothesizing that providing a way to access coverage reports without needing the GitHub app, how this could work, and if it could boost user adoption and engagement

#### Goals:

- Develop a mechanism that allows users to log in to Codecov and receive coverage data without requiring GitHub app installation.
- Test whether removing this barrier improves user adoption and overall experience toward adoption.
     - does self serve (6%yoy) meaningfully improve?  

## Discovery

- What does an appless Codecov experience look like?
- How can we deliver value to users without requiring the GitHub app?
- How do we transition users from an appless experience to adopting the GitHub app for full integration?
- What can we know if token is installed on repo, but not GH app?

#### Ideation:

- Develop a "team" concept or the ability to add organizations without GitHub app dependency.
- Explore methods to import repositories using team tokens.
- Alternative solutions for repository association without GitHub app installation.

#### Flow for ideation:

- Entity/team creation: User creates a team.
- System provides a token related to the entity/team.
- User connects a repository: What information does the system already know?

Figma: https://www.figma.com/design/SsoxtY2SB73l0wiLbJ8FhZ/GH-2092?node-id=1-2

#### Met
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/2185
- [ ] https://github.com/codecov/engineering-team/issues/2214
- [ ] https://github.com/codecov/internal-issues/issues/691
- [ ] https://github.com/codecov/engineering-team/issues/2526
- [x] Investigate: what orgs we can or cannot access before installing the app
- [x] (to be decide) Can we open PR for updating tokens after Codecov app has been installed (probably not)
- [ ] Invite member to view the repo without install the app
- [x] Question: do we want to increase a team bot usage? yes
```
ric or success criteria:
- ...

**Comment by codecovdesign** [comment]
assigning @calvin-codecov per slack thread, cc @Adal3n3 @katia-sentry

**Comment by Adal3n3** [comment]
8/9 From the security discussion meeting with @eliatcodecov @codecovdesign @rohan-at-sentry @aj-codecov @jeff-a-holland-codecov @trent-codecov @matt-codecov 

Next step, we want to investigate whether we can use the GH OIDC setup route to determine if we can access a repo from a member of an org with or without a token. We also want to clarity on what orgs we can or cannot access before installing the app.

https://github.com/codecov/internal-issues/issues/691

**Comment by Adal3n3** [comment]
Synced with @thomasrockhu-codecov on 9/10 to get priority for this investigation. Aiming to deliver the issue 691 by the end of September but need to double check with @nora-codecov to confirm a delivery date.

I'm going to mark this issue as blocked by the [OIDC setup investigation](https://github.com/codecov/internal-issues/issues/691) for now.

**Comment by thomasrockhu-codecov** [comment]
Confirming that we have set a delivery on end of the month. However, building out an OIDC setup is complicated, and there is a little more risk involved now.

**Comment by Adal3n3** [comment]
Meeting note 9/27 with @eliatcodecov @calvin-codecov @spalmurray-codecov:
- We will support adding a new repo by using the CLI only.
- Each repo will have a unique user upload token (repo token) per user. Once the app is installed, it will generate a repo token. This means that if a repo has two users, each user will have their own unique repo token for the same repo.
- Users will not be required to have admin access to add the token as a repo secret, but we will say it as the preferred step.
- Next step, Adalene will schedule a design review and include @matt-codecov for token related input.

(cc @codecovdesign @aj-codecov @rohan-at-sentry )

**Comment by Adal3n3** [comment]
10/16: reviewed with Eli, Trent, Matt, Spenser, Katia, Rohan, AJ. 

- Make ensure the install Codecov CTA is loud and clean on the PAT mode.
- Warn user if their PAT doesn't have an expiration date.
- This is an experimentation and we will track the adoption rate closely after it rollout.

Here's the latest design: https://www.figma.com/design/SsoxtY2SB73l0wiLbJ8FhZ/GH-2092?node-id=1-2

Token approaches notion doc from Matt: https://www.notion.so/sentry/Tokens-or-alternatives-for-Appless-Uploads-1158b10e4b5d80e59fdbccb7c976548b

**Comment by Adal3n3** [comment]
Appless discovery is completed. Moving forward we use this issue: https://github.com/codecov/engineering-team/issues/2679
