### ISSUE TITLE
Show coverage by flag inline

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#216]
## Problem to solve
In the former UI and at some parts of the migration the UI had a coverage by flags display option. This no longer seems to appear in the UI, therefore users are unable to view coverage details by flag in the file explorer. 

## Solution
Show coverage by flag filter in areas of inline viewing, so user may see flag specific reports.

[View designs](https://www.figma.com/file/USX2qBjfXNDrV11RCGbvcI/GH-3?type=design&node-id=5%3A1306&mode=design&t=QGMdfrYD46NRxDDA-1)
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/217
- [ ] https://github.com/codecov/engineering-team/issues/218
- [ ] https://github.com/codecov/engineering-team/issues/220
- [ ] https://github.com/codecov/engineering-team/issues/221
- [ ] https://github.com/codecov/engineering-team/issues/222
- [ ] https://github.com/codecov/engineering-team/issues/226
- [ ] https://github.com/codecov/engineering-team/issues/649
```

**Comment by katia-sentry** [comment]
[Applications] On track, should be complete this sprint
