### ISSUE TITLE
Implement Flag Based Coverage View on Commits Page

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#221]
We need to enhance the commits page to allow users to view coverage by flag when they are any tab on the commits page and have the flag passed along in the API request. This entails adding a new multi-select that shows all the flags associated with the given repository as per the [designs](https://l.codecov.dev/6OPSoG).

In the case where a selected flag does not exist or has no associated coverage data, display a message: "No coverage data available for the selected flag" or "The selected flag does not exist."

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/342
- [ ] https://github.com/codecov/engineering-team/issues/343
- [ ] https://github.com/codecov/engineering-team/issues/582
- [ ] https://github.com/codecov/engineering-team/issues/344
- [ ] https://github.com/codecov/engineering-team/issues/345
- [ ] https://github.com/codecov/engineering-team/issues/346
- [ ] https://github.com/codecov/engineering-team/issues/347
- [ ] https://github.com/codecov/engineering-team/issues/348
- [ ] https://github.com/codecov/engineering-team/issues/674
- [ ] https://github.com/codecov/engineering-team/issues/673
- [ ] https://github.com/codecov/engineering-team/issues/687
```

**Comment by nicholas-codecov** [comment]
Completed with codecov/gazebo/pull/2334
