### ISSUE TITLE
Hackweek: Codecov Dark Mode

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#2318]
https://github.com/codecov/gazebo/pull/3136

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/2338
- [ ] https://github.com/codecov/engineering-team/issues/2337
- [ ] https://github.com/codecov/engineering-team/issues/2321
- [ ] https://github.com/codecov/engineering-team/issues/2320
- [ ] https://github.com/codecov/engineering-team/issues/2319
- [ ] https://github.com/codecov/engineering-team/issues/2326
- [ ] https://github.com/codecov/engineering-team/issues/2327
- [ ] https://github.com/codecov/engineering-team/issues/2324
- [ ] https://github.com/codecov/engineering-team/issues/2340
- [ ] https://github.com/codecov/engineering-team/issues/2336
- [ ] https://github.com/codecov/engineering-team/issues/2334
- [ ] https://github.com/codecov/engineering-team/issues/2335
- [ ] https://github.com/codecov/engineering-team/issues/2333
- [ ] https://github.com/codecov/engineering-team/issues/2330
- [ ] https://github.com/codecov/engineering-team/issues/2329
- [ ] https://github.com/codecov/engineering-team/issues/2332
- [ ] https://github.com/codecov/engineering-team/issues/2322
- [ ] https://github.com/codecov/engineering-team/issues/2343
- [ ] https://github.com/codecov/engineering-team/issues/2360
- [ ] https://github.com/codecov/engineering-team/issues/2328
- [ ] https://github.com/codecov/engineering-team/issues/2371
- [ ] https://github.com/codecov/engineering-team/issues/2374
- [ ] https://github.com/codecov/engineering-team/issues/2372
- [ ] https://github.com/codecov/engineering-team/issues/2386
- [ ] https://github.com/codecov/engineering-team/issues/2385
- [ ] https://github.com/codecov/engineering-team/issues/2323
- [ ] https://github.com/codecov/engineering-team/issues/2403
- [ ] https://github.com/codecov/engineering-team/issues/2404
- [ ] https://github.com/codecov/engineering-team/issues/2462
```
