### ISSUE TITLE
QA everything

### ISSUE THREAD

**Issue by ajay-sentry** [codecov/engineering-team#2323]
```[tasklist]
### Tasks
- [x] https://github.com/codecov/engineering-team/issues/2351
- [ ] https://github.com/codecov/engineering-team/issues/2352
- [ ] https://github.com/codecov/engineering-team/issues/2350
- [ ] https://github.com/codecov/engineering-team/issues/2364
- [ ] https://github.com/codecov/engineering-team/issues/2368
- [ ] https://github.com/codecov/engineering-team/issues/2353
- [ ] https://github.com/codecov/engineering-team/issues/2354
- [ ] https://github.com/codecov/engineering-team/issues/2361
- [ ] https://github.com/codecov/engineering-team/issues/2355
- [ ] https://github.com/codecov/engineering-team/issues/2363
- [ ] https://github.com/codecov/engineering-team/issues/2367
- [ ] https://github.com/codecov/engineering-team/issues/2370
- [ ] https://github.com/codecov/engineering-team/issues/2373
- [ ] https://github.com/codecov/engineering-team/issues/2379
- [ ] https://github.com/codecov/engineering-team/issues/2382
- [ ] https://github.com/codecov/engineering-team/issues/2383
- [ ] https://github.com/codecov/engineering-team/issues/2384
- [ ] https://github.com/codecov/engineering-team/issues/2358
- [ ] https://github.com/codecov/engineering-team/issues/2405
```
