### ISSUE TITLE
Coverage over time for Components

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#234]
Successful implementation of 'Coverage over Time for Components' feature

Problem to solve:
- We have no ability to view component data over time and no ability in the UI to get a point in time view of component coverage without filtering on the file tree. 

Solution:
- Similar to the flags tab, we should display component coverage over time graphically. This should include an ability to click from the name of a component through to see a filtered view of the files like we did with the flags tab. 

Flags tab for reference:
![image](https://github.com/codecov/engineering-team/assets/95712206/c3fe9371-7ac1-41a5-980a-0668c213556f)

Figma: [link](https://www.figma.com/file/lpCAamL0oUGKvVng0g7vex/GH-234?type=design&node-id=1-2&mode=design)
Notion: [link](https://www.notion.so/sentry/UX-Coverage-over-time-for-Components-4b8c24a8f17444d0bf73978a007cee8e?pvs=4)
Notion technical: [link](https://www.notion.so/sentry/Components-Over-Time-a1d4856bd18a48318e6a06d16700b55c)
```[tasklist]
### Planning
- [ ] https://github.com/codecov/engineering-team/issues/1280
```

```[tasklist]
### Backend
- [ ] https://github.com/codecov/engineering-team/issues/1358
- [ ] https://github.com/codecov/engineering-team/issues/1359
- [ ] https://github.com/codecov/engineering-team/issues/1368
- [ ] https://github.com/codecov/engineering-team/issues/1360
- [ ] https://github.com/codecov/engineering-team/issues/1361
- [ ] https://github.com/codecov/engineering-team/issues/1362
- [ ] https://github.com/codecov/engineering-team/issues/1432
- [ ] https://github.com/codecov/engineering-team/issues/1601
```

```[tasklist]
### Gazebo
- [ ] https://github.com/codecov/engineering-team/issues/1383
- [ ] https://github.com/codecov/engineering-team/issues/1370
- [ ] https://github.com/codecov/engineering-team/issues/1374
- [ ] https://github.com/codecov/engineering-team/issues/1369
- [ ] https://github.com/codecov/engineering-team/issues/1373
- [ ] https://github.com/codecov/engineering-team/issues/1376
- [ ] https://github.com/codecov/engineering-team/issues/1377
- [ ] https://github.com/codecov/engineering-team/issues/1371
- [ ] https://github.com/codecov/engineering-team/issues/1379
- [ ] https://github.com/codecov/engineering-team/issues/1380
- [ ] https://github.com/codecov/engineering-team/issues/1381
- [ ] https://github.com/codecov/engineering-team/issues/1378
- [ ] https://github.com/codecov/engineering-team/issues/1382
- [ ] https://github.com/codecov/engineering-team/issues/1375
- [ ] https://github.com/codecov/engineering-team/issues/1372
- [ ] https://github.com/codecov/engineering-team/issues/1517
- [ ] https://github.com/codecov/engineering-team/issues/1602
- [ ] https://github.com/codecov/engineering-team/issues/1603
- [ ] https://github.com/codecov/engineering-team/issues/1635
- [ ] https://github.com/codecov/engineering-team/issues/1636
- [ ] https://github.com/codecov/engineering-team/issues/1639
- [ ] https://github.com/codecov/engineering-team/issues/1642
- [ ] https://github.com/codecov/engineering-team/issues/1666
- [ ] https://github.com/codecov/engineering-team/issues/1702
```

```[tasklist]
### Testing
- [ ] https://github.com/codecov/engineering-team/issues/1545
- [ ] https://github.com/codecov/engineering-team/issues/1461
```

**Comment by codecovdesign** [comment]
Discovery to ready for dev of brings components to the repo level

**Comment by codecovdesign** [comment]
### rough notes from components audit session 2/13/24 about flags and components:

Areas worth looking at related to flags and new components section:
- Feedback issue: https://github.com/codecov/feedback/issues/27
     - If looking for components feedback Nikos at Unity might help
          - Feedback: would like to select specific flag/component and see the specific data around that (on repo page data + ability to share that saved view)
- Config status
     - Not configured: https://app.codecov.io/gh/codecov/gazebo/flags
     - Configured in yaml, but needs processing: https://app.codecov.io/gh/codecov/codecov-action/flags
     - Configured in yaml and UI: https://app.codecov.io/gh/codecov/codecov-cli/flags
- Information architecture
     - Where to place flags
          - Separate sections?
          - Same section?
               - What could describe both “Grouping” “Breakdown” “Filters” “Flags and Components”
- Filters
- Flags trend line
     - Color is constant pink for now, should be revisited
- Ability to delete
     - Nuance is that is only deletes from the UI
     - Not sure if this is required for the component side of things?
