### ISSUE TITLE
Test Results Aggregate Improvements

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/engineering-team#2465]
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/2466
- [ ] https://github.com/codecov/engineering-team/issues/2467
- [ ] https://github.com/codecov/engineering-team/issues/2468
- [ ] possibly add functionality for ordering and filtering of aggregator functions (assuming we're going to have to piece multiple querysets together)
```
