### ISSUE TITLE
[TA] UI Support Work

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2528]
General work to support the UI. @joseph-sentry to provide more context.

```[tasklist]
### UI Support Work
- [ ] https://github.com/codecov/worker/pull/734
- [ ] https://github.com/codecov/engineering-team/issues/2532
- [ ] https://github.com/codecov/engineering-team/issues/2533
- [ ] https://github.com/codecov/engineering-team/issues/2534
- [ ] https://github.com/codecov/engineering-team/issues/2068
- [ ] https://github.com/codecov/codecov-api/pull/813
- [ ] https://github.com/codecov/codecov-api/pull/816
- [ ] https://github.com/codecov/codecov-api/pull/821
- [ ] https://github.com/codecov/codecov-api/pull/824
- [ ] https://github.com/codecov/codecov-api/pull/829
- [ ] https://github.com/codecov/codecov-api/pull/834
```

**Comment by Adal3n3** [comment]
Note on 10/1 from @joseph-sentry sync we might take a week to close this issue. 

All the 5 APIs has been completed but not yet merged.  #734 need to be merged first in order to start the backfill work
