### ISSUE TITLE
Post Slack app release fast follows

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#266]
Now that the Slack app is launched there’s a variety of additional tweaks we’d like to continue making.
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/268
- [ ] https://github.com/codecov/engineering-team/issues/270
- [ ] https://github.com/codecov/engineering-team/issues/271
- [ ] https://github.com/codecov/engineering-team/issues/265
- [ ] https://github.com/codecov/engineering-team/issues/261
- [ ] https://github.com/codecov/engineering-team/issues/263
- [ ] https://github.com/codecov/internal-issues/issues/94
- [ ] https://github.com/codecov/engineering-team/issues/272
```
