### ISSUE TITLE
Improve Codecov Onboarding for Github orgs  to better drive admins to install the Codecov App

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#2679]
Our onboarding flow for repos and orgs on Github requires an admin to approve installation of the Codecov Github App on the org in question. If a user (not an admin) is looking to try Codecov before making the case to their admin (or other stakeholders), currently they don't see much value.

The path forward would be to 

- Encourage admins to install the app and make that messaging front & center
- If a user is not an admin, guide them to an alternative path to get value out of codecov.

Figma (the latest design): https://www.figma.com/design/SsoxtY2SB73l0wiLbJ8FhZ/GH-2092?node-id=1-2

Here's an overview of the entire flow. Please go to figma or the breakdown issues for more details:

![Image](https://github.com/user-attachments/assets/eb82b6ec-fe16-456e-84e4-693a716a97e8)

```[tasklist]
### V1 - Install the app flow without PAT experience
- [ ] https://github.com/codecov/engineering-team/issues/2840
- [ ] https://github.com/codecov/engineering-team/issues/2828
- [ ] https://github.com/codecov/engineering-team/issues/2735
- [ ] https://github.com/codecov/engineering-team/issues/2734
- [ ] https://github.com/codecov/engineering-team/issues/2740
- [ ] https://github.com/codecov/engineering-team/issues/2984
- [ ] https://github.com/codecov/engineering-team/issues/2985
- [ ] https://github.com/codecov/engineering-team/issues/2986
- [ ] https://github.com/codecov/engineering-team/issues/3174
- [ ] https://github.com/codecov/engineering-team/issues/3228
```

```[tasklist]
### V2 - PAT experience
- [ ] https://github.com/codecov/engineering-team/issues/3239
- [ ] https://github.com/codecov/engineering-team/issues/2736
- [ ] https://github.com/codecov/engineering-team/issues/2739
- [ ] https://github.com/codecov/engineering-team/issues/2737
- [ ] https://github.com/codecov/engineering-team/issues/2741
- [ ] https://github.com/codecov/engineering-team/issues/2738
- [ ] https://github.com/codecov/engineering-team/issues/3235
- [ ] Storing PAT- security and legal discussion
```

```[tasklist]
### Doc
- [ ] https://github.com/codecov/engineering-team/issues/2742
- [ ] PAT doc for details setup instruction w gh screenshots
- [ ] From Matt: mention somewhere in the doc that the PAT will be stored encrypted in Codecov database.
```

```[tasklist]
### Growth Metrics
- [ ] https://github.com/codecov/internal-issues/issues/969
- [ ] https://github.com/codecov/internal-issues/issues/970
- [x] sign up to the first commit conversion rate - revisit
```

**Comment by calvin-codecov** [comment]
Notion doc: https://www.notion.so/sentry/Appless-Q4-Project-Planning-Non-PAT-1448b10e4b5d8004b5acd9150beba989?pvs=4

**Comment by aj-codecov** [comment]
Completed as scoped in Q4
