### ISSUE TITLE
Codecov will support "Login with Sentry" functionality

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#292]
KPI

functionality to link codecov account to sentry with oauth flow supported

stretch: sign in/up with Sentry
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/224
- [ ] https://github.com/codecov/engineering-team/issues/298
- [ ] https://github.com/codecov/engineering-team/issues/225
- [ ] https://github.com/codecov/engineering-team/issues/422
- [ ] https://github.com/codecov/gazebo/pull/2235
- [ ] https://github.com/codecov/engineering-team/issues/476
```
