### ISSUE TITLE
Update nav, header, and related elements

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#293]
## Problem to solve

_context: the nav element (not to confuse with org-selector>breadcrumb) was mostly untouched through the migration (was a former pattern on GH we mirrored). Today, those migration constraints have been lifted and present an opportunity to improve the nav/header/elements relationship. current UX: navigating the app starts at the org selection; then as user navigates there is a persistent breadcrumb:_

The problem is the nav is not serving as a navigation tool, but rather displaying external links (doc, support, blog). Important items, but they are secondary and raises question whether they take precedent in the top nav?

While the elements do see some high traffic (pendo reporting), they may be equally or more as effective in alternative context/location (or out of the way for primary nav). Additionally, the org selector and resulting breadcrumb are persistant as user navigates app; but visually are sub-nav (secondary) from the top-nav (primary). While this is a pattern familiar on repo providers (GH/GL); for our purposes this may be unnecessary to be visualized as secondary. Other questions to looks at:
 

- Is the “All orgs and repos” view helpful? is it worth constraining to specific org selection?
     - Consider we seen UX bugs with adding plan to wrong org
     - For third part apps, its familiar to be restricted to org context only
     - If this was removed, where could the plan page live (when org is not selected) 

- Consideration on how the top nav and header appear for both signed in and not signed in experience.
     - For not sign in experience, there is a high visibility and marketing opportunity of features (think open source dev that may use be interested in their org)

Ask for pendo related data to marketing team when ready to start this work.

## Solution and discovery ideation
<details><summary>ideation details</summary>
- Look at merging current org selection > breadcrumb to top nav
- Reconsider use and location of other elements
     - docs, support, blog, and feedback
     - profile dropdown (related to Pavillion updates, but better to be captured here)
- Revisit previous user testing:
     - We didn’t see major nav/breadcrumb issues in the testing; however, we did see some short-lived confusion and opportunity for potentially applying improved visual treatment on the org selector. 
     - Removing elements reduces visual friction
     - We did see users navigate to docs from the top nav. 

- Previously look at left-nav to show persistent org selector (common pattern that allows for selector + other in-app items + external links). Downsides are 1) large overhaul/UX change, 2) departure from current learned pattern (not gradual change), 3) constrains, or reduces the body container width allowed.
     - Worth visualizing wireframe for for team feedback/exploration, but the downsides are pretty high
</details>

🎨 [design overview](https://www.figma.com/file/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?type=design&node-id=178%3A443&mode=design&t=SpsRKeZfF5q4XXnh-1)

- [Latest design](https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385)

https://github.com/codecov/engineering-team/assets/87861036/008fc73a-fcdc-44a9-b28d-f02ce5f7203f

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/1858
- [ ] https://github.com/codecov/engineering-team/issues/1933
- [ ] #1934
- [ ] #1935
- [ ] #1936
- [ ] #1940
- [ ] #1941
- [ ] #1942
- [ ] #1951
- [ ] #1952
- [ ] #1953
- [ ] #1954
- [ ] #1955
- [ ] #1956
- [ ] https://github.com/codecov/engineering-team/issues/2066
- [ ] #1958
- [ ] #1959
- [ ] #1960
```

Nice-to-haves:
- [ ] #1943 
- [ ] #1944
- [ ] #1945 
- [ ] #1946 
- [ ] #1947 
- [ ] #1948 (low effort)
- [ ] #1957 (debatably)

**Comment by katia-sentry** [comment]
[Applications] Deprioritized this quarter

**Comment by codecovdesign** [comment]
@Adal3n3 from our sync to prep this issue for `dev ready`
- not logged in state related issue: https://github.com/codecov/engineering-team/issues/426
- related epic about branch: https://github.com/codecov/engineering-team/issues/1598
- supports: https://github.com/codecov/engineering-team/issues/1537

**Comment by Adal3n3** [comment]
Here's the [latest design](https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385) and please view the design mocks for more details.

- The font-size for Org selector remains “text-xl/Semibold”, but please double check the consistency across different plans.
- On the footer, add "[Submit a Github issue](https://github.com/codecov/feedback/issues/new/choose)" link for free plan customers only. No change on the paid plans.
- Enlarge font size to “text-xl/Semibold” for Repo breadcrumb.
- We have an on-going investigate branch display on breadcrumb https://github.com/codecov/engineering-team/issues/1600
- The placement of a topBanner should stick to the top of the nav bar.

![Screenshot 2024-05-20 at 8 37 04 AM](https://github.com/codecov/engineering-team/assets/152432831/bcceb0fd-8fec-4765-94f9-df578e9ce892)

@codecovdesign @spalmurray-codecov @katia-sentry

**Comment by Adal3n3** [comment]
Making a note from the slack 🧵: [link](https://sentry.slack.com/archives/C04MDUBCPHU/p1716296403036909)
- We need to regroup and relocate the support links from the footer to the new support icon/dropdown
- relocate the Sentry widget

![Screenshot 2024-05-21 at 10 50 58 AM](https://github.com/codecov/engineering-team/assets/152432831/271aee4c-d955-4910-8494-1b1d3c01e070)
![Screenshot 2024-05-21 at 10 51 39 AM](https://github.com/codecov/engineering-team/assets/152432831/868f2dff-db4e-45f9-a99b-7e60eebd16d4)
![Screenshot 2024-05-21 at 10 52 07 AM](https://github.com/codecov/engineering-team/assets/152432831/095e5163-2529-4a70-9170-b6e85d35ca6f)

**Comment by Adal3n3** [comment]
Making a note here from the sync with @spalmurray-codecov @nicholas-codecov @katia-sentry 5/23:
- Components will be use in this update: Breadcrumb, multi-selection, link with outbound link icon
- On the onboarding flow, we will remove top nav and add "back" and "cancel" button to make customers focus on the flow. We will keep the sentry feedback widget on the onboarding screens with no change.
- Sentry feedback widget will be reposition to the new support links icon.
- New footer, all links center-aligned the page.

Figma: [link](https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385)
