### ISSUE TITLE
Audit: Test Analytics

### ISSUE THREAD

**Issue by Adal3n3** [codecov/engineering-team#3106]
12/7 Product Audit video: [link](https://drive.google.com/file/d/1xnHmFaEWS7rVASaerJ6fOy6vTXp8afv9/view?usp=sharing)

```[tasklist]
### Tasks
- [ ] Need to provide token instruction (should not assume user knows how to setup token)
- [ ] 🐢 Slow loading in the UI to display empty state
- [ ] [On hold] Should mention you need to upload coverage report before upload test report on the onboarding page (but this will change in Q1)
```
