### ISSUE TITLE
Update for Seat Allocation and Upgrade Messaging

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#324]
## Problem to Solve:
Users are landing on specific pages without a clear understanding of their seat status, leading to confusion. Today, the page looks like an error, but in reality it's an access issue related to the org plan. While this appears as an error to the developers, it's actually an opportunity for the app to help them improve org's seat management and/or upgrade to paid plan. 
Related bug fix in-progress: https://github.com/codecov/engineering-team/issues/160

<img width="3252" alt="problem_to_solve" src="https://github.com/codecov/engineering-team/assets/87861036/9d51b680-7e82-4afa-9b2e-703c4296f4d7">

## Solution ideation

An informative and actionable UI copy to guide users based on their specific scenarios.

##### In-app

1. Paid Plan, No Available Seats
     - Display message about the seat limitation.
     - Provide an option or suggestion to increase the seat count.
2. Paid Plan, User Unactivated
     - Clearly state that there's an available seat, but user activation is needed.
     - Implement an activation toggle/button for the user.
3. Developer Free Plan, Seat Occupied
     - Emphasize that the plan includes only one seat, which is already occupied.
     - Highlight the option to add seats by upgrading.
4. Org > repo page
     - scenario w/ active repos when 1) developer isn’t activated, 2) developer/free plan
          - Allow any member at any time to view the setup repo page.
          - In initial iteration or later iteration can advertise upgrade.
     - Not yet setup repo (unpaid plan and/or not activated user)

<details><summary>early ideation</summary>
<img width="1165" alt="app_overview" src="https://github.com/codecov/engineering-team/assets/87861036/ec411130-cbb2-40b2-ba49-2fd72499a165">
</details>

<img width="1167" alt="app_overview_ii" src="https://github.com/codecov/engineering-team/assets/87861036/42bc3866-f13f-40c7-87ec-8b5ce714224e">

[view designs](https://www.figma.com/file/w7YrwirUx2fAtHaJhSnV0Q/no_more_seats?type=design&node-id=26%3A471&mode=design&t=iVLlOzv4eqVRtrVe-1)

additionally, keep breadcrumb visible and persistent for developer context.

##### PR comment
tbd

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/461
- [ ] https://github.com/codecov/engineering-team/issues/462
- [ ] https://github.com/codecov/engineering-team/issues/1253
- [ ] https://github.com/codecov/engineering-team/issues/1260
- [ ] https://github.com/codecov/engineering-team/issues/1299
- [ ] https://github.com/codecov/engineering-team/issues/1320
- [ ] https://github.com/codecov/engineering-team/issues/1414
- [ ] https://github.com/codecov/engineering-team/issues/1689
```

**Comment by codecovdesign** [comment]
Notes 2/23 kyle and rola
- Kyle: design ToDo separate to each condition 
- Rola: in order to show the breadcrumb we'll need to reevaluate our hooks to update the existing error, may not be complicated. 
- task breakdown iteration 1
     - problem: for repos that are not configured (private), currently users will be unable to view.
          - UPDATE: allow these repos to be viewed regardless of plan/authorization; HOWEVER, the hooks apply after it's configured. 
     - problem: active/plan status on active repos block 1> user ability to view tabs including bundles
          - UPDATE: allow private repos to be visible in terms of the tabs, if configured there should an empty
