### ISSUE TITLE
Updating the repositoryDeprecated to repository

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#355]
As part of fixing https://github.com/codecov/engineering-team/issues/160, we need to have Gazebo switch over from using the `repositoryDeprecated` resolver to using the `repository` resolver and handling the `NotFoundError` and `OwnerNotActivatedError`.

```[tasklist]
### Tasks
- [x] Remove from useBranch
- [x] Remove from useComponentComparison
- [x] Remove from usePullPageData
- [x] Remove from usePullHeadData
- [x] Remove from useCommitPageData
- [x] Remove from useBranches
- [x] Remove from useBranchCoverageMeasurements (Spencer)
- [x] Remove from useCommitHeaderData
- [x] Remove from usePulls
- [x] Remove from useCommit
- [x] Remove from useCommitYaml (Spencer)
- [x] Remove from useCompareTotals
- [x] Remove from useCommitErrors (Ajay)
- [x] Remove from useCommits (Rola)
- [x] Remove from useComparisonForCommitAndParent (Ajay)
- [x] Remove from useCoverageWithFlags
- [x] Remove from useFileWithMainCoverage
- [x] Remove from usePrefetchBranchDirEntry - Nick
- [x] Remove from useRepoBranchContents - Nick
- [x] Remove from usePrefetchCommitDirEntry
- [x] Remove from useRepoCommitContents
- [x] Remove from usePrefetchPullDirEntry
- [x] Remove from useRepoPullContents
- [x] Remove from usePrefetchSingleFileComp - Nick
- [x] Remove from usePull
- [x] Remove from useSingularImpactedFileComparison (Rola)
- [x] Remove from useRepo
- [x] Remove from useRepoBackfilled (Ajay)
- [x] Remove from useRepoConfig (Ajay)
- [x] Remove from useRepoCoverage (Spencer)
- [x] Remove from useRepoFlags (rohit)
- [x] Remove from useRepoFlagsSelect (rohit)
- [x] Remove from useRepoOverview
- [x] Remove from useRepoSettings (rohit)
- [x] Remove from useCoverageWithFilters - Nick
- [x] Remove from api.test.js - Nick
- [x] usePrefetchBranchFileEntry - Nick
```
