### ISSUE TITLE
Post-Trial Changes

### ISSUE THREAD

**Issue by adrian-codecov** [codecov/engineering-team#357]
These are changes/fixes we want to keep track of post trial release, sorted by importance.

```[tasklist]
### API Tasks
- [ ] https://github.com/codecov/engineering-team/issues/359
- [ ] https://github.com/codecov/engineering-team/issues/362
- [ ] https://github.com/codecov/engineering-team/issues/363
- [ ] https://github.com/codecov/engineering-team/issues/423
``` 

```[tasklist]
### Clent Tasks
- [ ] https://github.com/codecov/engineering-team/issues/361
- [ ] https://github.com/codecov/engineering-team/issues/360
- [ ] https://github.com/codecov/engineering-team/issues/358
- [ ] https://github.com/codecov/engineering-team/issues/349
- [ ] https://github.com/codecov/engineering-team/issues/387
- [ ] https://github.com/codecov/engineering-team/issues/391
- [ ] https://github.com/codecov/engineering-team/issues/406
- [ ] https://github.com/codecov/engineering-team/issues/399
- [ ] https://github.com/codecov/engineering-team/issues/677
- [ ] https://github.com/codecov/engineering-team/issues/746
```
