### ISSUE TITLE
Slack notifications filters enhancement

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#377]
Enhance Slack notifications to support multiple filters by refactoring and migrating the current notification table structure.

> Functional approach:
> - New notification table that is unique by channel, repo and owner, has an array field filters
> - New Notification status table, we remove channel as it will be tied to the new notification
> - Script to loop old notifications channels and statuses to append to new notifications 
> - We create a Django command to migrate old data to new data
> - Make sure the current prod code is reading from the old tables but populating BOTH the old table and the new table
> - Run backfill command
> - Update the code to read from the new table
> - Drop the old table

more context: https://github.com/codecov/engineering-team/issues/265#issuecomment-1683821510
```[tasklist]
### Tasks
- [x] Create new notifications and notifications status tables
- [ ] Populate the new table with new notifications
- [ ] Create a backfill command to migrate old notification enteries to the new one
```
