### ISSUE TITLE
Launch ATS as a Beta offering for Python Repos

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#397]
Work with customers to understand and address pain points around first time setup and general use of ATS. Goals

1. At least 1 customer should be able to set up ATS on their repo without any assistance from Codecov
2. 10 customers using ATS by end of quarter (October 31, 2023)

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/feedback/issues/60
- [ ] https://github.com/codecov/engineering-team/issues/407
- [ ] https://github.com/codecov/codecov-cli/issues/238
- [ ] https://github.com/codecov/engineering-team/issues/449
- [ ] https://github.com/codecov/engineering-team/issues/456
- [ ] https://github.com/codecov/codecov-cli/issues/243
- [ ] https://github.com/codecov/engineering-team/issues/470
- [ ] https://github.com/codecov/engineering-team/issues/471
- [ ] https://github.com/codecov/engineering-team/issues/472
- [ ] https://github.com/codecov/engineering-team/issues/478
- [ ] https://github.com/codecov/engineering-team/issues/526
- [ ] https://github.com/codecov/engineering-team/issues/555
```
