### ISSUE TITLE
Review GH Issues for PII & Labeling for Open Source Contribution

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#428]
**1. Review GH Issues for PII** 
Please review issues in the assigned range for any mentions of customers or PII. Remove or ask for help as needed.

Look for: developer names, usernames, or contact details like email addresses, employee IDs, IP addresses, domain names, API keys, passwords, internal server details, configurations, database specifics, sensitive logs.

Look for edited comments and/or if you have to edit a comment, you will need to remove the revision history as well see screenshot: 
![image](https://github.com/codecov/engineering-team/assets/87821126/550ed001-ca02-47c6-b07d-be14f045200a)

**2. Labeling for Open Source Contribution**
Identify straightforward and low priority issues (open issues only), and add the "good first issue" label for open source contributors.

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/429
- [ ] https://github.com/codecov/engineering-team/issues/430
- [ ] https://github.com/codecov/engineering-team/issues/431
- [ ] https://github.com/codecov/engineering-team/issues/432
- [ ] https://github.com/codecov/engineering-team/issues/433
- [ ] https://github.com/codecov/engineering-team/issues/434
- [ ] https://github.com/codecov/engineering-team/issues/435
- [ ] https://github.com/codecov/engineering-team/issues/436
- [ ] https://github.com/codecov/engineering-team/issues/437
- [ ] https://github.com/codecov/engineering-team/issues/438
- [ ] https://github.com/codecov/engineering-team/issues/439
- [ ] https://github.com/codecov/engineering-team/issues/440
- [ ] https://github.com/codecov/engineering-team/issues/441
- [ ] https://github.com/codecov/engineering-team/issues/442
- [ ] https://github.com/codecov/engineering-team/issues/443
- [ ] https://github.com/codecov/engineering-team/issues/444
```
