### ISSUE TITLE
Add ability to disable non OKTA login

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#450]
Customers using OKTA will likely want to disable the ability to login to Codecov via VCS providers directly. 

```[tasklist]
### Tasks
- [ ] Add config option for disabling non okta login
- [ ] Functionality in place to disable based on config option
- [ ] Documentation updated/provided for this config option
```
