### ISSUE TITLE
A

### ISSUE THREAD

**Issue by terry-codecov** [codecov/engineering-team#484]
103~ occurrences

Effort estimate: hard

A is an abstraction on top of the navigation services and the AppLink component. To convert this properly to TypeScript the 3 other dependencies should be converted. Separate PRs for each file is likely a good approach to keep the changes easier to review.

Suggested PR ordering: 
* useStaticLinks (with correct type narrowing)
* useNavLinks (with correct type narrowing)
* AppLink
* A

```[tasklist]
### Tasks
- [ ] Convert AppLink to TypeScript
- [ ] Convert useStaticNavLinks to TypeScript
- [ ] Convert useNavLinks
- [ ] Convert A to TypeScript
```

Note: There is an import rule preventing services being imported into UI components as part of the architecture design. The ideal solution is to  exempt `import type {..} from '....'` from this rule or to one off ignore that rule for this this type only import.
