### ISSUE TITLE
CodeRenderer [Blocked by A, CopyClipboard, Progress, TotalsNumber,  Label ]

### ISSUE THREAD

**Issue by terry-codecov** [codecov/engineering-team#490]
45 occurrences
Effort estimate: hard

This one is very intermingled with shared fileviewer.  Mostly just a large volume of related files and components.

```[tasklist]
### Tasks
- [ ] CodeRenderer hooks folder
- [ ] InfoRow
- [ ] ProgressHeader
- [ ] CoverageLineIndicator
- [ ] CriticalFileLable
- [ ] DiffLin
- [ ] FileHeader
- [ ] SingleLine
- [ ] CodeRenderer
- [ ] shared/utils/prismLanguageMapper
- [ ] shared/utils/unsupportedExtensionsMapper
- [ ] shared/utils/fileviewer
```

**Comment by terry-codecov** [comment]
Blocked by https://github.com/codecov/engineering-team/issues/500
