### ISSUE TITLE
Plan for refactoring old tables to new table UI

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#532]
Plan + issues for replacing existing tables with new table. 

- Turn this issue into epic 
- Add issues to action on plan
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/583
- [ ] https://github.com/codecov/engineering-team/issues/592
- [ ] https://github.com/codecov/engineering-team/issues/585
- [ ] https://github.com/codecov/engineering-team/issues/587
- [ ] https://github.com/codecov/engineering-team/issues/589
- [ ] https://github.com/codecov/engineering-team/issues/591
- [ ] https://github.com/codecov/engineering-team/issues/584
- [ ] https://github.com/codecov/engineering-team/issues/586
- [ ] https://github.com/codecov/engineering-team/issues/590
- [ ] https://github.com/codecov/engineering-team/issues/588
- [ ] https://github.com/codecov/engineering-team/issues/593
- [ ] https://github.com/codecov/engineering-team/issues/594
- [ ] https://github.com/codecov/engineering-team/issues/595
- [ ] https://github.com/codecov/engineering-team/issues/596
- [ ] https://github.com/codecov/engineering-team/issues/597
- [ ] https://github.com/codecov/engineering-team/issues/598
- [ ] https://github.com/codecov/engineering-team/issues/599
- [ ] https://github.com/codecov/engineering-team/issues/600
- [ ] https://github.com/codecov/engineering-team/issues/601
- [ ] https://github.com/codecov/engineering-team/issues/602
- [ ] https://github.com/codecov/engineering-team/issues/603
```
