### ISSUE TITLE
Team Plan - MVP

### ISSUE THREAD

**Issue by adrian-codecov** [codecov/engineering-team#604]
Refer to designs [here](https://www.figma.com/file/YayQHDiX9uY7J7MVTtsVFX/Codecov-Light-Plan?type=design&node-id=1-4&mode=design&t=s8YKbsNNzt5Tbfpr-0) and discussions [here](https://www.notion.so/sentry/Multiple-Tiers-40acddfc0968442b83a4c8b85c2720c7) and [here](https://www.notion.so/Users-Lite-Plan-patch-only-c2ed9dc8955642caadef8d5c8563402b)

All client tickets will need to be under a feature flag, lets call it `multipleTiers`.

```[tasklist]
### Client Tasks
- [ ] https://github.com/codecov/engineering-team/issues/633
- [ ] https://github.com/codecov/engineering-team/issues/726
- [ ] https://github.com/codecov/engineering-team/issues/632
- [ ] https://github.com/codecov/engineering-team/issues/714
- [ ] https://github.com/codecov/engineering-team/issues/718
- [ ] https://github.com/codecov/engineering-team/issues/719
- [ ] https://github.com/codecov/engineering-team/issues/628
- [ ] https://github.com/codecov/engineering-team/issues/613
- [ ] https://github.com/codecov/engineering-team/issues/723
- [ ] https://github.com/codecov/engineering-team/issues/608
- [ ] https://github.com/codecov/engineering-team/issues/725
- [ ] https://github.com/codecov/engineering-team/issues/685
- [ ] https://github.com/codecov/engineering-team/issues/625
- [ ] https://github.com/codecov/engineering-team/issues/614
- [ ] https://github.com/codecov/engineering-team/issues/615
- [ ] https://github.com/codecov/engineering-team/issues/606
- [ ] https://github.com/codecov/engineering-team/issues/684
- [ ] https://github.com/codecov/engineering-team/issues/634
- [ ] https://github.com/codecov/engineering-team/issues/683
- [ ] https://github.com/codecov/engineering-team/issues/607
- [ ] https://github.com/codecov/engineering-team/issues/616
- [ ] https://github.com/codecov/engineering-team/issues/690
- [ ] https://github.com/codecov/engineering-team/issues/618
- [ ] https://github.com/codecov/engineering-team/issues/619
- [ ] https://github.com/codecov/engineering-team/issues/617
- [ ] https://github.com/codecov/engineering-team/issues/687
- [ ] https://github.com/codecov/engineering-team/issues/697
- [ ] https://github.com/codecov/engineering-team/issues/686
- [ ] https://github.com/codecov/engineering-team/issues/623
- [ ] https://github.com/codecov/engineering-team/issues/622
- [ ] https://github.com/codecov/engineering-team/issues/621
- [ ] https://github.com/codecov/engineering-team/issues/624
- [ ] https://github.com/codecov/engineering-team/issues/620
- [ ] https://github.com/codecov/engineering-team/issues/626
- [ ] https://github.com/codecov/engineering-team/issues/727
- [ ] https://github.com/codecov/engineering-team/issues/636
- [ ] https://github.com/codecov/engineering-team/issues/627
- [ ] https://github.com/codecov/engineering-team/issues/739
- [ ] https://github.com/codecov/engineering-team/issues/743
- [ ] https://github.com/codecov/engineering-team/issues/635
```

```[tasklist]
### API Tasks
- [ ] https://github.com/codecov/engineering-team/issues/246
- [ ] https://github.com/codecov/engineering-team/issues/639
- [ ] https://github.com/codecov/engineering-team/issues/408
- [ ] https://github.com/codecov/engineering-team/issues/409
- [ ] https://github.com/codecov/engineering-team/issues/412
- [ ] https://github.com/codecov/engineering-team/issues/411
- [ ] https://github.com/codecov/engineering-team/issues/638
- [ ] https://github.com/codecov/engineering-team/issues/713
- [ ] https://github.com/codecov/engineering-team/issues/724
- [ ] https://github.com/codecov/engineering-team/issues/731
- [ ] https://github.com/codecov/engineering-team/issues/637
- [x] https://github.com/codecov/engineering-team/issues/805
```
