### ISSUE TITLE
Continue working on the Bundle Analysis Plugin

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#721]
Continue working away on the the plugin for Rollup, Vite, and Webpack.
```[tasklist]
### Completed
- [x] Scaffold out various packages
- [x] Initialize bundler core package
- [x] Initialize rollup package
- [x] Initialize vite package
- [x] Initialize webpack package
- [x] Generate stats information in rollup plugin
- [x] Generate stats information in vite plugin
- [x] Generate stats information in webpack plugin
- [x] Gather environment vars from various CI providers
- [x] Figure out upload strategy in bundler core
- [x] Get CI Up and running
- [x] Grab provider information using utils
- [x] Upload Stats In Bundler Core
- [x] Figure out/implement testing strategy for bundler core utils
- [x] Setup Pre-commit utils
- [x] Remove commit sha from getPreSignedURL as it's just passed through the body
- [x] Update getPreSignedURL to `/upload/bundle_analysis/v1`
- [x] Make sure licenses are all correct
- [x] Create snapshot tests for webpack plugin
- [x] Create snapshot tests for vite plugin
- [x] Create snapshot tests for rollup plugin
- [x] Update bundler core readme
- [x] Update rollup readme
- [x] Update vite readme
- [x] Update webpack read
- [x] Update project readme
- [x] Add bundle option to give upload a bundle name
- [x] Normalize path names
- [x] Setup release flow
```

```[tasklist]
### Todo
- [ ] Add integration tests for older bundler versions
- [ ] Remove any webpack 4 stuff - for v0
- [ ] Add Sentry to bundler core for errors, traces, and ddm
```

**Comment by nicholas-codecov** [comment]
Closing in favour of issues being made in #741
