### ISSUE TITLE
Filter coverage by components

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#760]
Show coverage by component filter in areas of inline viewing, so user may see component specific reports.

**Problem to solve:**
There is currently no way to view component coverage within the codecov UI beyond the component coverage of a PR or Commit. If you'd like to drill down into what files make up those components you don't have any ability to do so.

**Ideal Outcome:**
We build a multiselect dropdown for a user to choose a component or components to filter their coverage to. This will give users deeper visibility into their components. 
It should include a dropdown:
- on the coverage tab above the file tree
- on the PR Detail view (same places where we put a flag filter)
- on the commit details view (same places where we put a flag filter)
- On an individual file level
  - The nuance here is that this selector is simply is/is not included in a component, there is no way to more granularly breakdown coverage of a file by component smaller than a whole file. 

**Other Context:**
- Components are only specified in a codecov.yml file, they are specified via file path(s)
- Docs: https://docs.codecov.com/docs/components
- We've used a cog so far to symbolize components, but that looks like a settings icon - we may need something else, or maybe not, just a thought

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/779
- [ ] https://github.com/codecov/engineering-team/issues/824
- [ ] https://github.com/codecov/engineering-team/issues/825
- [ ] https://github.com/codecov/engineering-team/issues/826
- [ ] https://github.com/codecov/engineering-team/issues/827
- [ ] https://github.com/codecov/engineering-team/issues/829
- [ ] https://github.com/codecov/engineering-team/issues/831
- [ ] https://github.com/codecov/engineering-team/issues/832
- [ ] https://github.com/codecov/engineering-team/issues/835
- [ ] https://github.com/codecov/engineering-team/issues/838
- [ ] https://github.com/codecov/engineering-team/issues/839
- [ ] https://github.com/codecov/engineering-team/issues/840
- [ ] https://github.com/codecov/engineering-team/issues/841
- [ ] https://github.com/codecov/engineering-team/issues/842
- [ ] https://github.com/codecov/engineering-team/issues/843
- [ ] https://github.com/codecov/engineering-team/issues/844
- [ ] https://github.com/codecov/engineering-team/issues/845
- [ ] https://github.com/codecov/engineering-team/issues/852
- [ ] https://github.com/codecov/engineering-team/issues/856
- [ ] https://github.com/codecov/engineering-team/issues/857
- [ ] https://github.com/codecov/engineering-team/issues/858
- [ ] https://github.com/codecov/engineering-team/issues/859
- [ ] https://github.com/codecov/engineering-team/issues/860
- [ ] https://github.com/codecov/engineering-team/issues/861
```

Design link: https://www.figma.com/file/eEUnkfHa5DGGuYVwZkCV7R/GH-760?type=design&node-id=1-340&mode=design&t=ZxSv4xtd87XlERvw-0
