### ISSUE TITLE
Okta for Enterprise Cloud

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#763]
Enterprise customers are looking for single-sign in with Okta as a featured offering.

As a pre-requisite, we will need a way to [associate multiple providers with a given user](https://github.com/codecov/engineering-team/issues/762).

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/internal-issues/issues/157
- [ ] https://github.com/codecov/engineering-team/issues/908
- [ ] https://github.com/codecov/engineering-team/issues/1533
```

**Comment by katia-sentry** [comment]
blocked by https://github.com/codecov/engineering-team/issues/762

**Comment by aj-codecov** [comment]
Currently don't have the concept of a Codecov "org" - we currently rely on providers for permissions. 
Associating multiple providers - we don't have the UI to fluidly move between multiple providers - this alone does not make Okta possible in Enterprise Cloud.
"Users want Okta to control access to something owned by an org"
Do we store and manage users/org relationships within our DB? - yes
We can currently tie Okta to users, but we can't tie Okta to _orgs_ - permissions are constrained to an owner
Codecov admin will need to help configure Okta
- domain
- email domain
- other info?
To work like a normal Okta implementation we'd need to keep track of emails and their connection to an org

If you don't see an org - we can force SSO by acknowledging a user's GH relationship to that org and prompting login. 

Steps:
1. Create DB schema to link Okta org to an Owner in Owner's table - **Platform**
2. UI to allow a Codecov admin to connect Okta (and disconnect if desired), admins will need to add Codecov to their Okta org as well outside of Codecov - **Applications**
4. Okta login where you specify email address > route to Okta login - **Platform/Applications?**
5. Update access models to restrict org visibility to only showing up when Okta is used. - **Platform?/Applications**
6. Inform users to use okta if they have not and we know they have a connection to a GH org that requires Okta - **Applications**

**Comment by jerrodcodecov** [comment]
AJ comments from Slack:

This was me taking notes during a meeting so it’s not the clearest write up - an admin persona would need to set up Okta for an org and give us both their email domain(s) and Okta details for connection, the only thing we’d need to actually hide behind that login is private repos for an org. We can tell if a user is on an org and what permissions they have and trigger Okta login as needed (when trying to view a private repo for example). This is my recollection - CC

**Comment by codecovdesign** [comment]
closing this as it's captured in this epic (applications + platform): https://github.com/codecov/engineering-team/issues/908
