### ISSUE TITLE
Team Plan - MVP Bugs

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#771]
MVP - https://github.com/codecov/engineering-team/issues/604
Fast follows - https://github.com/codecov/engineering-team/issues/769

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/780
- [ ] https://github.com/codecov/engineering-team/issues/781
- [ ] https://github.com/codecov/engineering-team/issues/782
- [ ] https://github.com/codecov/engineering-team/issues/788
- [ ] https://github.com/codecov/engineering-team/issues/786
- [ ] https://github.com/codecov/engineering-team/issues/783
- [ ] https://github.com/codecov/engineering-team/issues/785
- [ ] https://github.com/codecov/engineering-team/issues/787
- [ ] https://github.com/codecov/engineering-team/issues/808
- [ ] https://github.com/codecov/engineering-team/issues/790
- [ ] https://github.com/codecov/engineering-team/issues/821
```
