### ISSUE TITLE
Get ats action usable

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#791]
Work with Tom to make the ATS action better. Ideally we should be able to dogfood it internally. 
```[tasklist]
### Tasks
- [ ] 1 action for all things ATS
- [ ] Intelligent base picking
- [ ] Ensure ATS action and Docker action works for all codecov repos
- [ ] https://github.com/codecov/engineering-team/issues/854
```

**Comment by giovanni-guidini** [comment]
[draft] Create a super command for ATS and use it in the action.
