### ISSUE TITLE
ATS Dashboard view for repos not using ATS (leads to growth in usage)

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#811]
**Objective**
Seamless on-boarding to ATS

**Problem**
Currently, developers have no idea Codecov ATS is in beta. This is because
1. We send emails to a single leader persona (most likely)
2. The docs for ATS are buried in "guides" (which is the right place, but you have to know what you're looking for)

[We've recently introduced a nudge in the PR comment footer,](https://github.com/codecov/worker/pull/165) but we see opportunities to further improve how people become aware of ATS and start onboarding.

**Solution**

For the initial iteration: [view design](https://www.figma.com/file/Jmgi69GDiIYZ4LLmgrPmXo/Test-Selection-In-App-Experiment?type=design&node-id=50%3A120&mode=design&t=pryOSizq3zmysoUX-1)

- show not yet configured and configured states
     - applies conditionally only to repos that contain python
     -  IF not yet configured, copy described feature + anchors to documentation
     - IF configured, copy confirms configuration status + solicits feedback ([issue here](https://github.com/codecov/feedback/issues/173))

| not yet configured | configured |
|-----------------|-----------------|
| <img width="1471" alt="ATS_inapp_concept_NOTCONFIGURED" src="https://github.com/codecov/engineering-team/assets/87861036/f4465ed2-76f5-4f75-9bf5-a5355ef4d706">  | <img width="1471" alt="ATS_inapp_concept_CONFIGURED" src="https://github.com/codecov/engineering-team/assets/87861036/ba36a66d-3c2e-4f94-b665-a8ff62c57536"> |

     
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/900
- [ ] https://github.com/codecov/engineering-team/issues/929
- [ ] https://github.com/codecov/engineering-team/issues/930
- [ ] https://github.com/codecov/engineering-team/issues/931
- [ ] https://github.com/codecov/engineering-team/issues/932
- [ ] https://github.com/codecov/engineering-team/issues/933
- [ ] https://github.com/codecov/engineering-team/issues/934
```

**Comment by rohan-at-sentry** [comment]
https://www.figma.com/file/Jmgi69GDiIYZ4LLmgrPmXo/Test-Selection-In-App-Experiment?type=design&node-id=24-130&mode=design&t=TVICHTKshyrnDsAx-0

**Comment by Adal3n3** [comment]
@codecovdesign The label "Automate Tests" on the menu tab should be "Test selection". (cc @rohan-at-sentry)

**Comment by codecovdesign** [comment]
@Adal3n3 makes sense! updated ✅
