### ISSUE TITLE
Have parsers

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#816]
```[tasklist]
### Tasks
- [ ] JUnit XML parser
- [ ] pytest-reportlog parser
- [ ] Vitest JSON parser
```

**Comment by joseph-sentry** [comment]
Not sure if doing the Jest JSON parser is worth it at the moment, we'd like to have duration information for each testcase being run, but the Jest JSON reporter only gives duration at a testsuite granularity
