### ISSUE TITLE
API and worker are able to ingest files (based on what worker needs for comment)

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#818]
```[tasklist]
### Tasks
- [ ] Figure out what data we need
- [ ] Create tables that reflect the data we need
- [ ] Update worker logic to ensure data access (create new UploadProcessor task)
- [ ] Update API upload endpoint and upload task in worker
```
