### ISSUE TITLE
Codecov has a unified local development experience

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#82]
Revamp [umbrella](https://github.com/codecov/umbrella) to meet the needs of the wider org. 

Goals
* Environment can be stood up in 1-2 commands
* Environment handles secrets
* Documentation created to clarify usage
* Environment can be run with as few local projects as desired
```[tasklist]
### Tasks
- [ ] https://github.com/codecov/umbrella-hat/issues/11
- [ ] https://github.com/codecov/umbrella-hat/issues/14
- [ ] https://github.com/codecov/umbrella-hat/issues/13
- [ ] https://github.com/codecov/umbrella-hat/issues/12
```
