### ISSUE TITLE
Filter location and UI visual

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#836]
## Problem to solve
As we've iterated on the commit and pull pages, we've added tabs + filters (components, flags) + key. This collected some ux debt and the visual on UI is running into issues:

- The filter and key appear even when unrelated tabs are active (tabs unrelated to displaying files)
- There are spacing issues with the elements, worsened by lower screen sizes. 

<img width="1109" alt="Screenshot 2023-11-20 at 6 36 23 AM" src="https://github.com/codecov/engineering-team/assets/87861036/ef4dcbc8-3896-4809-9369-e9eeb92e392c">

## Solution ideation

- Reorganize filter locations and key so they are together and consistent across pages
- The key and filter should only be visible for related files pages
- Consider empty states when there are no files needed and visibility of elements

[WIP designs for review](https://www.figma.com/file/JQm5j1act2qRnknTDHbJbG/GH-836?type=design&node-id=1%3A239&mode=design&t=1pKU4YnFoKoicbo5-1)

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/893
- [ ] https://github.com/codecov/engineering-team/issues/1186
- [ ] https://github.com/codecov/engineering-team/issues/1281
- [ ] https://github.com/codecov/engineering-team/issues/1282
- [ ] https://github.com/codecov/engineering-team/issues/1283
- [ ] https://github.com/codecov/engineering-team/issues/1284
- [ ] https://github.com/codecov/engineering-team/issues/1285
- [ ] https://github.com/codecov/engineering-team/issues/1286
- [ ] https://github.com/codecov/engineering-team/issues/1287
- [ ] https://github.com/codecov/engineering-team/issues/1281
```

**Comment by katia-sentry** [comment]
Sync with @codecovdesign to help with discovery. The designs are there, but not finalized

**Comment by codecovdesign** [comment]
@rohitvinnakota-codecov per our breakdown moving this to `dev ready` cc @katia-sentry

**Comment by katia-sentry** [comment]
Tasks
- [x] https://github.com/codecov/engineering-team/issues/893
- [x] https://github.com/codecov/engineering-team/issues/1186
- [x] https://github.com/codecov/engineering-team/issues/1281
- [x] https://github.com/codecov/engineering-team/issues/1282
- [x] https://github.com/codecov/engineering-team/issues/1283
- [x] https://github.com/codecov/engineering-team/issues/1284
- [x] https://github.com/codecov/engineering-team/issues/1285
- [x] https://github.com/codecov/engineering-team/issues/1286
- [x] https://github.com/codecov/engineering-team/issues/1287
- [x] https://github.com/codecov/engineering-team/issues/1281


cc. @rohitvinnakota-codecov

**Comment by codecovdesign** [comment]
report related to this issue: https://github.com/codecov/engineering-team/issues/1417
