### ISSUE TITLE
support creating SQL metrics that can be grouped/filtered by arbitrary metadata (customer, repo, api endpoint, http response)

### ISSUE THREAD

**Issue by matt-codecov** [codecov/engineering-team#879]
```[tasklist]
### Tasks
- [x] SQL models for postgres/alloydb and timescale https://github.com/codecov/shared/pull/72
- [x] initialize django in worker so django telemetry models can be used https://github.com/codecov/worker/pull/168
- [ ] https://github.com/codecov/engineering-team/issues/919
- [ ] https://github.com/codecov/terraform/issues/1080
- [ ] choose between postgres/alloydb and timescale, delete the one not chosen
```
