### ISSUE TITLE
[Client] Create hooks to fetch data for bundle analysis summary

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#992]
We need to fetch some basic information to generate the dropdown summary string. We can grab the `missesCount` and `partialsCount` fields from the `patchTotals` object on the `Comparison` type in GraphQL. From this hook we will want to return the sum of the two values or return 0 if there is no missing lines.

Designs can be found [here](https://www.figma.com/file/IeW6e2YY0vwjIjlHYCBFac/Bundle-Analysis?type=design&node-id=500%3A2685&mode=design&t=EKIqDc0lUYlbTE52-1).

---

```[tasklist]
### Tasks
- [x] Create hook to fetch bundle analysis summary data for a given commit
- [x] Create hook to fetch bundle analysis summary data for a given PR
```

---

```[tasklist]
### Blocked by
- [ ] https://github.com/codecov/engineering-team/issues/960
- [ ] https://github.com/codecov/engineering-team/issues/959
```
