### ISSUE TITLE
[Client] Create bundle analysis tables

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/engineering-team#994]
We need to create two bundle analysis tables one for a given commit and one for a given PR.

Designs can be found [here](https://www.figma.com/file/IeW6e2YY0vwjIjlHYCBFac/Bundle-Analysis?type=design&node-id=500%3A2685&mode=design&t=EKIqDc0lUYlbTE52-1).

---

The data being displayed in the table is as follows:

- Bundle name
- Bundle previous size
- Bundle new size
- Bundle size change

---

```[tasklist]
### Tasks
- [ ] Create bundle analysis table for a given commit
- [ ] Create bundle analysis table for a given PR
```

---

```[tasklist]
### Blocked by
- [ ] https://github.com/codecov/engineering-team/issues/993
```
